let danhSachPhim = [
    {
        "id": "phim1",
        "ten": "Kẻ hủy diệt: thời đại genisys",
        "theLoai": "Phim hành động, Phim viễn tưởng",
        "nhaSanXuat": "Paramount Pictures, Skydance Media, Annapurna Pictures",
        "noiDung": "Kẻ hủy diệt (The Terminator) là một bộ phim điện ảnh ra mắt khán giả vào năm 1984 thuộc thể loại hành động/khoa học viễn tưởng của đạo diễn James Cameron, đồng tác giả là Cameron và William Wisher Jr với các diễn viên Arnold Schwarzenegger, Linda Hamilton và Michael Biehn. Bộ phim được sản xuất bởi Hemdale Film Corporation và được phân phối bởi Orion Pictures, và quay tại Los Angeles. <br> <br> Schwarzenegger thủ vai Kẻ hủy diệt/Người máy hủy diệt, một nhân vật danh nghĩa, một sát thủ người máy sinh học dường như không thể ngăn chặn, được siêu máy tính điện toán có trí thông minh nhân tạo gửi về năm 1984 từ năm 2029 nhằm để giết Sarah Connor, vai diễn của Linda Hamilton. Michael Biehn, thủ vai Kyle Reese, một người lính của Phe kháng chiến đi ngược thời gian để bảo vệ Sarah. <br> <br> Phần 5 của Kẻ hủy diệt (thời đại genisys) sẽ tập trung vào sự kiện trước khi Sarah Connor biến mất vào khoảng giữa Terminator 2: Judgment Day và Terminator 3: Rise of the Machines. Trong khoảng thời gian này người xem sẽ tiếp xúc với hình hài thật sự của Kẻ hủy diệt T-800 ở dạng con người, và đồng nghĩa với việc sau này tại sao hình mẫu của nhân vật được Skynet lựa cho các lần đưa về quá khứ sau này.",
        "thoiLuong": "126 phút",
        "namSanXuat": "2015",
        "anh": "KeHuyDiet.jpg",
            "IMDb": "6.4",
            "daoDien": "Alan Taylor",
            "dienVien": "Arnold Schwarzenegger, Jason Clarke, Emilia Clarke, Jai Courtney, J. K. Simmons, Dayo Okeniyi, Matt Smith, Courtney B. Vance, Lee Byung-hun",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "trailer": "ePuIk7Vk0QY",
            "review":"Có thể nói rằng năm 2015 là một năm tuyệt vời nhất đối với bất kì một tín đồ yêu điện ảnh nào trên thế giới khi mà hoàng loạt các bộ phim bom tấn đều không hẹn mà gặp và được cùng công chiếu trong năm nay. Trong những tháng đầu hè vừa qua, khi mà sức nóng tại các rạp chiếu phim do Avengers: Age of Ultron cùng Jurassic World gây ra còn chưa kịp hạ nhiệt thì nay chúng ta lại được chào đón thêm một siêu phẩm khác - Terminator: Genisys.có thể đánh giá tổng thể như sau: Phim phù hợp với những tín đồ của thể loại hành động với mật độ các cảnh \"chặt chém\", cháy nổ dày đặc. Nội dung phim khá ổn, tuy nhiên có lẽ sẽ làm mếch lòng khá nhiều tín đồ yêu thích và \"cuồng\" Terminator từ những phần đầu tiên, lý do vì sao thì tôi sẽ tiết lộ đôi chút ở cuối bài review sau (Bạn yên tâm đi, không spoil đâu!)<br><br>Đánh giá chung như vậy cũng có lẽ là tạm đủ rồi, bây giờ, chúng ta hãy cùng nhau đánh giá chi tiết hơn một chút và chấm điểm cụ thể về Terminator: Genisys nhé.<br><br>KỸ XẢO: Có thể nói rằng sự lôi cuốn của bất kì một bộ phim viễn tưởng nào cũng đều phụ thuộc khá nhiều vào chất lượng kỹ xảo được sử dụng trong phim và điều này cũng không ngoại lệ đối với Terminator: Genisys.Kỹ xảo trong phim được đầu tư khá kỹ lưỡng và chi tiết với chủ đạo là các cảnh tàn phá, rượt đuổi trong thành phố. Riêng về phần tuyến nhân vật đáng chú ý nhất là các Terminator thì thực sự không có quá nhiều điểm nổi bật so với các phần trước của phim, bạn sẽ vẫn được chứng kiến sự đối đầu của những cỗ máy hủy diệt thực sự trong hình hài con người và tất nhiên là độ bền của họ thì vẫn như các phần phim trước <br><br>CỐT TRUYỆN: Như đã tóm tắt ở trên, nội dung của phim khá ổn với những nút thắt được biên kịch phim lồng ghép suốt trong nửa đầu phim. Tuy nhiên, việc hầu hết các nút thắt này được hé lộ quá nhiều trong trailer và gần như được giải quyết toàn bộ trong nửa đầu phim khiến cho nửa sau của Terminator: Genisys gần như chỉ mang tính hành động thuần túy mà thôi bởi kết thúc thì ai cũng biết rồi. (lúc nào phe con người cũng phải thắng thôi!)<br>Một điểm trừ nữa của phim như tôi đã nói ở trên, đó là phim sẽ làm mất lòng khá nhiều fan trung thành của Terminator bởi đúng như những gì mà nhà sản xuất đã spoil trước đó, hai nhân vật chính Sarah và Kyle của chúng ta sẽ phải lập trình lại một phiên bản tương lai hoàn toàn khác (điều này cũng khá dễ hiểu bởi chính quá khứ của Sarah cũng đã bị thay đổi rồi còn đâu). Như vậy thì gần như những gì xảy ra trong các phần trước đều coi như... bỏ đi (Về khoản này thì người viết thấy khá giống với X-Men: Days of Future Past).<br><br>DIỄN VIÊN: Có lẽ phần bù trừ lại cho điểm yếu về nội dung của Terminator: Genisys chính là ở sự thể hiện khá tốt của dàn diễn viên tham gia. Arnold Schwarzenegger thì khỏi phải nói rồi, ông được sinh ra cho vai diễn T-800 và vẫn thể hiện quá tốt dù cho tuổi tác đã cao.<br>Duy chỉ có một điều đáng tiếc đó là diễn xuất của Arnold dường như không thay đổi quá nhiều. Vẫn sẽ là các màn chiến đấu đậm chất xôi thịt và cơ bắp, vẫn sẽ là câu nói đanh thép nổi tiếng \"Tôi sẽ trở lại\"... Do đó, bạn sẽ phải thất vọng một phen nếu mong chờ vào một hình ảnh Arnold khác biệt so với các phiên bản Terminator trước đây. Dẫu sao thì đây cũng là điều chấp nhận được bởi chúng ta không thể đòi hỏi quá nhiều khi mà giờ đây Arnold Schwarzenegger đã có tuổi và phong cách này cũng theo ông quá lâu rồi.<br><br>ÂM THANH: Điểm cộng tiếp theo của Terminator: Genisys chính là ở hiệu ứng âm thanh được sử dụng trong phim. Điểm nhấn vẫn sẽ là những cảnh hành động kịch tính với âm thanh dồn dập cùng nhạc phim hoành tráng. Những màn cháy nổ, va đập hay thậm chí tiếng kim loại va chạm khi hai robot chiến đấu vô cùng chân thực, đủ để làm hài lòng bất kì khán giả khó tính nào.<br>Nhìn chung thì Terminator: Genisys chưa thể coi là một tác phẩm quá xuất sắc nhưng dù sao thì với thời lượng dành cho các cảnh chiến đấu nhiều như vậy, phim vẫn là sự lựa chọn tuyệt vời cho những tín đồ ưa thích thể loại hành động kịch tính.",

    },
    {
        "id": "phim2",
        "ten": "Người nhện: Xa nhà",
        "theLoai": "Phim hành động, Phim viễn tưởng",
        "nhaSanXuat": "Columbia Pictures, Pascal Pictures, Marvel Studios",
        "noiDung": "Hậu chiến Vô Cực, Người Nhện Peter Parker và nhóm bạn thân cùng tham gia chuyến du lịch châu Âu của trường. Tuy nhiên, kế hoạch siêu anh hùng nghỉ phép của Peter nhanh chóng bị hủy bỏ sau khi cậu đồng ý giúp Nick Fury khám phá bí ẩn về những cuộc tấn công của nhóm kẻ thù mang sức mạnh nguyên tố đang tàn phá khắp lục địa.  <br><br> Người Nhện - Peter Parker tham gia chuyến du lịch châu Âu cùng bạn bè. Nhưng chuyến đi của cậu không hề suôn sẻ bởi trái đất đang đứng trước sự đe doạ của nhóm Elementals. Lần này, trong vai trò người bảo vệ mới của biệt đội Avengers thay Iron Man, Nhện sẽ phải tìm cách xoay sở trước kẻ thù để giữ lấy sự bình yên cho trái đất. Spider-Man và cư dân trái đất, tất cả mọi người đều phải học cách đối mặt và sống tiếp khi Iron Man đã không còn.",
        "thoiLuong": "134 phút",
        "namSanXuat": "2019",
        "anh": "NguoiNhen.jpg",
            "trailer": "sMxUb1A59MI",
            "IMDb": "7.6",
            "daoDien": "Jon Watts",
            "dienVien": "Tom Holland, Michael Keaton, Jon Favreau, Zendaya, Donald Glover, Tyne Daly, Marisa Tomei, Robert Downey Jr.",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "Sau hành động làm loạn vũ trụ như vậy đã xé một lỗ hổng không gian khiến những kẻ phản diện từ chiều không gian của đa vũ trụ khác có thể đến được với chiều thực tại của đội Avengers. Spider-man là thành viên duy nhất còn đang hoạt động tại Trái đất trong team Avengers, Nick Fury phải đến yêu cầu cầu bé Peter Parker nghênh chiến khi không còn sự lựa chọn nào khác để đảm nhận nhiệm vụ bảo vệ thế giới.<br><br>ĐÁNH GIÁ:<br>Có lẽ phải nói đến việc từ trước khi bình minh của vũ trụ điện ảnh Marvel bắt đầu thì Jake Gyllenhaal đã từng được chỉ định vào vai Spider-man. Quay trở mốc thời gian sau khi người Nhện của đạo diễn Sam Raimi ra đời, khi các cuộc đàm phán hợp đồng với Tobey Maguire trở nên vô cùng căng thẳng đến mức hãng Columbia Pictures đã nhanh chóng gửi lời đề nghị tới ngôi sao trẻ đang lên Jake Gyllenhaal để đóng vai anh hùng trong Spider-Man 2. Có lẽ giờ đây, Jake tham gia vào một phim của trong franchise Marvel là điều hợp lý mà thôi.<br><br>Gyllenhaal cuối cùng đã không bao giờ đảm nhận vai trò này và cuối cùng anh lại có một sự nghiệp thú vị hơn nhiều, với các dự án phim có các vai diễn rất đa dạng như Brokeback Mountain, Nightcrawler, and cả Okja…Trong phim Spider-Man: Far From Home, phần thứ hai trong series về Spidey, Gyllenhaal đẩm nhận vai Mysterio (có vẻ là một vai chính diện).<br><br>Một chiến binh mặc áo choàng nhung, xuất hiện như một thực tế bất thường khi anh mặc áo giáp màu xanh lá cây và đội mũ bảo hiểm hình hình cầu. Trong trailer phim, anh có màn biểu diễn xoay quanh một tên ác nhân và tung đòn ma thuật màu xanh. Nói cách khác, anh ấy khá kỳ quặc.Rõ ràng, đây là một bộ phim Người Nhện theo kiểu cũ thông thường, một bối cảnh trong vũ trụ điện ảnh Marvel với hậu quả sau sự kiện Avengers: Endgame. Peter Parker (Tom Holland)vẫn là một cậu nhóc tuổi teen ham chơi bên những người bạn MJ (Zendaya) và Ned (Jacob Batalon), tất cả bọn họ vẫn vô tình tiếp tục năm thứ hai trung học (hơi vô lý).<br><br>Peter lúc này đang vật lộn với việc liệu cậu ta có thể thay thế người anh hùng yêu dấu của mình – chú Tony (Iron Man) hay không? rồi cậu ta bị cuốn vào một cuộc phiêu lưu mới với Nick Fury (Samuel L. Jackson) và Mysterio. Người sẽ giúp đỡ cậu chiến đấu với một nhóm quái vật trên khắp châu Âu.<br><br>Cốt truyện này sẽ là câu chuyện Peter Parker sẽ giải quyết vấn đề để nhanh chóng trưởng thành ra sao, những điều thường ngày của cậu ta đối với MJ và những nỗ lực của cậu ta để giữ bí mật danh tính của mình với các bạn cùng lớp. Đạo diễn Jon Watts, người cũng thực hiện Homecoming, dựa vào cùng động lực ngớ ngẩn đã cung cấp cho bộ phim trước đó của ông; những bộ phim này thiếu đi sự vĩ đại của bộ ba Người Nhện nguyên bản Sam Raimi, nhưng họ nắm bắt được người anh hùng dũng cảm.<br><br>Cuối cùng, bộ phim Spider-man: Far From Home mang muốn mang đến một câu chuyện về việc làm thế nào để chiến thắng chính bản thân mình của Peter Parker. Người Nhện giờ đây phải tự mình đưa ra những lựa chọn quan trọng mà trước đây cậu ta hay trốn tránh. Tự thân đứng trước một trách nhiệm nặng nề và quan trọng, có nhiều thứ cộng hưởng về mặt cảm xúc, liệu Spider man sẽ giải quyết ra sao. Nếu như hoài nghi về công thức mà Marvel vẫn làm, thì có lẽ với Người Nhện: Xa Nhà, khán giả sẽ thấy cách Peter Parker sáng tạo để thoát ra khởi những rắc rối của tuổi vị thành niên.",

    },
    {
        "id": "phim3",
        "ten": "Na Tra: Ma đồng giáng thế",
        "theLoai": "Phim hoạt hình",
        "nhaSanXuat": "Coco Cartoon, Horgos Coloroom Pictures, October Media",
        "noiDung": "Từ thuở xa xưa, tinh hoa đất trời hội tụ thành một viên ngọc chứa đựng năng lượng khổng lồ. Nguyên Thủy Thiên Tôn đã phân tách viên ngọc này thành 1 viên Linh Châu và 1 viên Ma Hoàn. Viên Linh Châu sẽ đầu thai thành một anh hùng cứu thế, phò trợ nhà Chu. Trong khi đó, Ma Hoàn sẽ tạo ra một Ma Vương tàn sát thiên hạ. Để ngăn chặn thảm họa, Nguyên Thủy Thiên Tôn đã hạ chú để sau 3 năm Ma Vương sẽ bị Thiên kiếp tiêu diệt. Liệu Na Tra có đủ sức để thay đổi Thiên mệnh?",
        "thoiLuong": "110 phút",
        "namSanXuat": "2019",
        "anh": "NaTra.jpg",
            "IMDb": "7.8",
            "trailer": "yCJy9roIv8Q",
            "daoDien": "Yu Yang",
            "dienVien": "Lü Yanting, Joseph, Han Mo, Chen Hao, Lü Qi, Zhang Jiaming, Yang Wei",
            "quocGia": "Trung Quốc",
            "ngonNgu":"Tiếng Trung Quốc",
            "review": "Không phải ngẫu nghiên thị trường Trung Quốc dành rất nhiều lời khen ngợi cho Na Tra: Ma đồng tái thế; đồng thời các nhà phê bình và khán giả Việt cũng đánh giá cao tác phẩm này. Màn tái xuất của Na Tra lần này thực sự quá mức ấn tượng và xuất sắc từ cốt truyện cho tới hình ảnh, âm thanh và kỹ xảo.<br><br>Na Tra không phải là nhân vật xa lạ với nhiều người, thậm chí có đến khoảng 60% dân số nước ta biết đến Na Tra nhờ xem các bộ phim của anh bạn láng giềng phương bắc. Nhưng bộ phim lần này không phải tái hiện lại những gì đã từng xuất hiện trên màn ảnh. Thay vào đó mang đến một câu chuyện mới đầy thú vị về Na Tra từ khi cậu bé sinh ra cho đến khi hi sinh tính mạng mình để bảo vệ những người dân vô tội khi mới 3 tuổi.<br><br>CỐT TRUYỆN: Na Tra là bộ phim có phần kịch bản được xây dựng quá tốt khi kết hợp các yếu tố hài hước, vui vẻ với những bài học sâu sắc về cuộc sống, tình cảm bạn bè và tình cảm gia đình. Khán giả theo dõi phim sẽ liên tục được chứng kiến những đoạn thoại vô cùng hài hước và lầy lội đến từ Na Tra, thậm chí có một số bạn mải xem phim còn quên cả ăn bắp và uống nước. 60% thời lượng của bộ phim là những tình huống gây cười được xây dựng vô cùng khéo léo và tinh tế. 40% còn lại sẽ khiến cảm xúc của khán giả trùng xuống một chút khi đề cập đến tình cảm gia đình và những thông điệp ngắn gọn chỉ một câu nói thôi nhưng lại vô cùng ý nghĩa.<br><br> LỒNG TIẾNG: Na Tra hiện đang được công chiếu tại Touch Cinema với hai bản phụ đề và lồng tiếng. Touch Cinema đã xem xuất chiếu sớm và đánh giá rất cao phần lồng tiếng của dàn diễn viên trong phim, thể hiện đầy đủ mọi trạng thái cảm xúc nhân vật từ vui vẻ, lo lắng, hạnh phúc, cáu bẳn….Phần chuyển ngữ của bộ phim cũng được dịch vô cùng sát nghĩa với lời thoại gốc. Điều này cũng đã góp phần giúp bộ phim trở nên thú vị và hấp dẫn hơn. Đặc biệt là cảnh Na Tra làm thơ khi bị nhốt trong phòng, thoạt nghe tưởng vô lý nhưng lại hợp lý cực kỳ.<br><br>ÂM THANH, HÌNH ẢNH:<br>Chúng tôi đánh giá rất cao phần hình của của Na Tra trong phim. Rất nhiều góc quay được sử dụng giúp đặc tả trạng thái cảm xúc của cậu nhóc thông minh, lém lỉnh và có phần bất cần. Kết hợp với phần âm than được xử lý tốt, tận dụng được hệ thống loa vòm đa kênh của rạp nên mang đến những tiếng động vô cùng gần thũi và thân thuộc đối với khán giả.<br><br>Kỹ xảo phim Na Tra cũng được khán giả đánh giá rất cao với những cảnh ghép được xử lý đồ họa vô cùng mượt mà và ấn tượng. Mang đến cho khán giả một tác phẩm với phần hình ảnh đẹp xuất sắc. Vẫn còn một số lỗi về phần kỹ xảo của phim, tuy nhiên những lỗi này rất nhỏ nên không ảnh hưởng đến tổng thể chất lượng phim.",

    },
    {
        "id": "phim4",
        "ten": "Fast & Furious:HOBBS & SHAW",
        "theLoai": "Phim hành động",
        "nhaSanXuat": "Chris Morgan Productions, Seven Bucks Productions, Universal Pictures",
        "noiDung": "Sau 8 phim với phần doanh thu chạm mức 5 tỉ đô la Mỹ toàn cầu, giờ đây thương hiệu Fast & Furious sẽ trở lại với một phần ngoại truyện hoàn toàn độc lập với sự tham gia của Dwayne Johnson trong vai Luke Hobbs và Jason Statham trong vai Deckard Shaw trong Hobbs & Shaw.<br><br> Câu chuyện giữa hai người tưởng như không đội trời chung là Đặc vụ An ninh Ngoại giao Mỹ Luke Hobbs và tên tội phạm đánh thuê khét tiếng Deckard Shaw khi họ bất đắc dĩ phải bắt tay hợp tác nhằm ngăn chặn âm mưu của trùm phản diện cực nguy hiểm trong diện bí ẩn Brixton.",
        "thoiLuong": "137 phút",
        "namSanXuat": "2019",
        "anh": "fast.jpg",

        "IMDb": "6.6",
            "daoDien": "David Leitch",
            "trailer": "9SA7FaKxZVI",
            "dienVien": "Dwayne Johnson, Jason Statham, Idris Elba, Vanessa Kirby, Eiza González, Cliff Curtis, Helen Mirren",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "Fast & Furious: Hobbs & Shaw không phải là phần 9 của loạt phim ăn khách Fast & Furious, đây là một phần ngoại truyện riêng biệt về hai kẻ thù từng đánh nhau ra bã trong các phần trước là Luke Hobbs và Deckard Shaw. Còn Fast 9 chắc các bạn phải chờ dài dài vì dự án này đang gặp sự cố khi một diễn viên đóng thế gặp tai nạn. <br><br>Gây ấn tượng với khán giả bởi trailer phim đầy hài hước và những pha hành động khoe cơ bắp đầy mãn nhãn, Fast & Furious: Hobbs & Shaw đã khiến khán giả Touch Cinema phải canh từng phút để đặt được vé xem suất công chiếu sớm. Tất nhiên mọi kỳ vọng của khán giả đã không bị uổng phí, Hobbs và Shaw đã mang đến cho khán giả một tác phẩm hành động quá phê.<br><br>Nếu bạn kỳ vọng Fast & Furious: Hobbs & Shaw sẽ mang đến một câu chuyện hoàn toàn mới về chủ đề hành động, khác hẳn với những bộ phim đã từng công chiếu trước đó. Vậy thì các bạn sẽ phải thất vọng một chút, phim vẫn xoay quanh chủ đề giải cứu thế giới của một bộ phận “siêu anh hùng” nhưng cả thế giới gần như không ai biết đến họ.<br><br>Nửa đầu bộ phim có diễn biến khá chậm, tập trung vào khai thác cuộc sống của hai đặc vụ và những mâu thuẫn của cả hai trong quá khứ. Sau đó là quá trình xóa nhòa khúc mắc giữa cả hai, biến từ kẻ thù trở thành đồng đội và phối hợp với nhau đầy ăn ý khi thực hiện nhiệm vụ. Phần đầu dù nhịp phim không quá nhanh, các pha hành động cũng khá nhẹ nhàng nhưng lại truyền tải tâm lý, cảm xúc nhân vật rất tốt.<br><br>Nửa sau bộ phim giống như một thế giới khác khi tiết tấu phim được đẩy lên nhanh hơn, các pha hành động căng thẳng và kịch tính hơn, nhiều tình huống cao trào khiến khán giả phải thót tim vì sợ hãi. Chắc chắn rằng bạn sẽ vô thức thu gọn mình lại khi Shaw trổ tài lái xe điệu nghệ, lách mình thoát khỏi cánh cửa tử thần; hoặc bạn cũng sẽ không dám thở mạnh khi Hobbs treo lơ lửng bên bờ vực và suýt nữa mất xác dưới biển sâu. Tất cả những pha hành động đều mang đến cảm giác cực kỳ căng thẳng và thỏa mãn người xem.<br><br>KỊCH BẢN:<br>Fast & Furious: Hobbs & Shaw có phần kịch bản khá đơn giản, nếu so sánh với các phần Fast & Furious trước đó thì nội dung phim sẽ yếu hơn. Tuy nhiên bộ phim lại có những pha hành động cực kỳ ấn tượng nên những thiếu sót về mặt kịch bản có thể dễ dàng được bỏ qua. Bộ phim hoàn toàn xứng đáng để khán giả đến rạp xem phim, đặc biệt là theo dõi bản 3D.<br><br>DIỄN XUẤT<br>Dàn diễn viên chính của Fast & Furious: Hobbs & Shaw là những cái tên có tầm ảnh hưởng tại giới điện ảnh Hollywood và trên khắp thế giới. The Rock vai Luke Hobbs, Jason Statham vai Shaw, Vanessa Kirby vai Hattie,… đây đều là những gương mặt có hàng triệu fan tại khắp nơi trên thế giới. Họ chinh phục khán giả không chỉ bởi gương mặt hay cơ bắp, thay vào đó là kỹ năng diễn xuất đặc biệt điêu luyện.<br><br>ÂM THANH, HÌNH ẢNH:<br>Theo thang điểm 10, kỹ xảo của Fast & Furious: Hobbs & Shaw tối thiểu đạt 8/10. Tất cả những hình ảnh được xử lý cực kỳ đẹp mắt và chân thật, không mang đến cảm giác bị chỉnh sửa nhiều như các tác phẩm xử lý đồ họa khác. Các pha hành động nhờ vậy càng trở nên mãn nhãn và đẳng cấp. Để cảm nhận trọn vẹn sự hấp dẫn của các pha hành động, các bạn nên theo dõi bản 3D nhé.",

    },
    {
        "id": "phim5",
        "ten": "One Punch Man (Season 1)",
        "theLoai": "Phim hoat hình",
        "nhaSanXuat": "Asatsu, Bandai Namco Arts, Bandai",
        "noiDung": "Câu chuyện diễn ra tại thành phố Z, Nhật Bản. Thế giới đầy quái vật bí ẩn xuất hiện và gây ra nhiều thảm họa. Nhân vật chính Saitama (Onepunch Man), một siêu anh hùng dễ dàng đánh bại các quái vật hay những nhân vật phản diện khác chỉ với một cú đấm.Tuy nhiên, sau khi trở thành quá mạnh, Saitama đã trở nên nhàm chán trong những trận chiến của mình và luôn cố gắng để tìm đối thủ mạnh hơn để chiến đấu.<br><br> Trong cuộc phiêu lưu của mình, anh gặp những người bạn mới, kẻ thù, và đệ tử của riêng mình, Cyborg Genos và gia nhập Hiệp hội Anh hùng để tìm danh tiếng cho mình và thực thi công lý. Mặc dù đánh bại những con quái vật mạnh mẽ nhưng anh không được hiệp hội coi trọng, Saitama phải đấu tranh để có được thứ hạng của mình. Hầu hết mọi người phân biệt đối xử anh do cái đầu hói của mình và một số cho rằng anh là một anh hùng giả mạo. Chỉ có một số nhỏ người công nhận tài năng đáng kinh ngạc của Saitama.",
        "thoiLuong": "22 phút / tập (12 tập)",
        "namSanXuat": "2015",
        "anh": "OPM-1.jpg",

        "IMDb": "9.5",
        "trailer": "Poo5lqoWSGw",
            "daoDien": "Shingo Natsume",
            "dienVien": "Makoto Furukawa, Kaito Ishikawa, Yoji Ueda, Shoota Yamamoto, Hiroki Goto",
            "quocGia": "Nhật Bản",
            "ngonNgu":"Tiếng Nhật",
            "review": "Khi một bộ manga ra mắt thu hút lượng lớn độc giả, thì phiên bản anime cũng sẽ được ưa thích không kém. Nhưng đối với trường hợp One-Punch Man, phiên bản hoạt hình còn được các fan hâm mộ cuồng nhiệt hơn cả manga gốc.<br><br>Cốt truyện One-Punch Man xoay quanh cuộc sống của nhân vật Saitama – một thanh niên bình thường với mơ ước việc trở thành anh hùng chỉ là thú vui. Nhưng anh đã luyện tập quá nhiều và đạt đến cảnh giới cao đến mức bị rụng hết tóc và sở hữu sức mạnh kinh khủng có thể hạ gục đối thủ chỉ bằng một cú đấm.<br><br>Bộ truyện ban đầu được đăng tải miễn phí trên các trang web và diễn đàn manga và sau này được tác giả Yusuke Murata phát triển thành series dài hơi đăng lên tạp chí truyện tranh đình đám Shonen Jump. Điều khiến One-Punch Man nổi bật phải kể đến cách vẽ võ thuật rất khác lạ và sống động của Murata. Studio Madhouse đã đưa One-Punch Man lên màn ảnh một cách xuất sắc khi biến những khung truyện hành động của Murata thậm trí còn sống động và gay cấn hơn. <br><br>Ngoài ra, lý do khiến anime/manga này được yêu thích là cốt truyện hài hước, xoay quanh các nhân vật vui nhộn. Với mỗi quái vật tấn công quê hương Saitama, anh đều dễ dàng hạ gục. Sau đó Saitama cứu người máy Genos và thu nhận cậu làm đồ đệ. <br><br>Loạt nhân vật phản diện trong truyện cũng là nguồn vui của độc giả, chúng thường có ngoại hình hài hước và những tình huống họ đụng độ One-Punch Man cũng rất kỳ quặc. Hiện tác phẩm được đánh giá là manga/anime hấp dẫn nhất trong loạt truyện/phim hoạt hình hành động ra mắt gần đây tại Nhật Bản.",

    },
    {
        "id": "phim6",
        "ten": "One Punch Man (Season 2)",
        "theLoai": "Phim hoạt hình",
        "nhaSanXuat": "Asatsu, Bandai Namco Arts, Bandai",
        "noiDung": "Câu chuyện diễn ra tại thành phố Z của Nhật Bản tại thời điểm thế giới đầy những quái vật bí ẩn với sức mạnh ghê ghớm đã xuất hiện và gây ra biết bao nhiêu thảm họa. Nhưng cũng chính tại đây xuất hiện 1 siêu anh hùng đấm phát chết luôn, có thể dễ dàng đánh bại và tiêu diệt những con quái vật này. Cũng chính vì tài năng hiếm có này mà có rất nhiều nghi ngại về khả năng thực sự của vị siêu anh hùng, thậm chí anh không bao giờ nhận được bất kỳ lòng tin nào từ dân chúng.",
        "thoiLuong": "24 phút / tập (24 tập)",
        "namSanXuat": "2019",
        "anh": "OPM-2.jpg",

        "IMDb": "8.9",
        "trailer": "78ngg0SRlEI",
            "daoDien": "Shingo Natsume",
            "dienVien": "Makoto Furukawa, Kaito Ishikawa, Yoji Ueda, Shoota Yamamoto, Hiroki Goto",
            "quocGia": "Nhật Bản",
            "ngonNgu":"Tiếng Nhật",
            "review": "Khi một bộ manga ra mắt thu hút lượng lớn độc giả, thì phiên bản anime cũng sẽ được ưa thích không kém. Nhưng đối với trường hợp One-Punch Man, phiên bản hoạt hình còn được các fan hâm mộ cuồng nhiệt hơn cả manga gốc.<br><br>Cốt truyện One-Punch Man xoay quanh cuộc sống của nhân vật Saitama – một thanh niên bình thường với mơ ước việc trở thành anh hùng chỉ là thú vui. Nhưng anh đã luyện tập quá nhiều và đạt đến cảnh giới cao đến mức bị rụng hết tóc và sở hữu sức mạnh kinh khủng có thể hạ gục đối thủ chỉ bằng một cú đấm.<br><br>Bộ truyện ban đầu được đăng tải miễn phí trên các trang web và diễn đàn manga và sau này được tác giả Yusuke Murata phát triển thành series dài hơi đăng lên tạp chí truyện tranh đình đám Shonen Jump. Điều khiến One-Punch Man nổi bật phải kể đến cách vẽ võ thuật rất khác lạ và sống động của Murata. Studio Madhouse đã đưa One-Punch Man lên màn ảnh một cách xuất sắc khi biến những khung truyện hành động của Murata thậm trí còn sống động và gay cấn hơn. <br><br>Ngoài ra, lý do khiến anime/manga này được yêu thích là cốt truyện hài hước, xoay quanh các nhân vật vui nhộn. Với mỗi quái vật tấn công quê hương Saitama, anh đều dễ dàng hạ gục. Sau đó Saitama cứu người máy Genos và thu nhận cậu làm đồ đệ. <br><br>Loạt nhân vật phản diện trong truyện cũng là nguồn vui của độc giả, chúng thường có ngoại hình hài hước và những tình huống họ đụng độ One-Punch Man cũng rất kỳ quặc. Hiện tác phẩm được đánh giá là manga/anime hấp dẫn nhất trong loạt truyện/phim hoạt hình hành động ra mắt gần đây tại Nhật Bản.",

    },
    {
        "id": "phim7",
        "ten": "One Piece film: Z",
        "theLoai": "Phim hoạt hình",
        "nhaSanXuat": "Toei Animation Company",
        "noiDung": "Monkey D. Luffy, 1 cậu bé rất thích hải tặc có ước mơ tìm được kho báu One Piece và trở thành Vua hải tặc - Pirate King. Lúc nhỏ, Luffy tình cờ ăn phải trái quỷ (Devil Fruit) Gomu Gomu, nó khiến cho cơ thể cậu có khả năng co dãn đàn hồi như cao su nhưng đổi lại Luffy sẽ không bao giờ biết bơi. Sau đó Luffy lại được Shanks cứu thoát tuy nhiên vì thế ông ta bị mất 1 cánh tay. Shanks chia tay Luffy và để lại cho cậu một chiếc mũ rơm (Straw Hat). Câu chuyện bắt đầu khi Luffy 17 tuổi, cậu rời quê hương đi tìm đủ 10 thành viên để thành lập 1 nhóm cướp biển với tên gọi là Băng Hải tặc Mũ Rơm (Straw Hat Crew). Trên đường đi, cậu tìm thêm được các thành viên cho nhóm và đánh bại rất nhiều kẻ thù. <br><br> One Piece Film: Z là movie One Piece thứ 12, Bộ phim được đạo diễn bởi Tatsuya Nagamine và được giám sát bởi tác giả của bộ truyện One Piece Eiichiro Oda.",
        "thoiLuong": "108 phút",
        "namSanXuat": "2012",
        "anh": "OnePiece-Z.jpg",

        "IMDb": "8.0",
        "trailer": "1gGt1Mg_zSo",
            "daoDien": "Tatsuya Nagamine",
            "dienVien": "Mayumi Tanaka, Kazuya Nakai, Akemi Okamura, Kappei Yamaguchi, Hiroaki Hirata, Ikue Ohtani, Yuriko Yamaguchi, Kazuki Yao",
            "quocGia": "Nhật Bản",
            "ngonNgu":"Tiếng Nhật",
            "review": "Theo lời hãng phim Toei thì tác phẩm mới sẽ là lúc để đối thủ mạnh nhất của băng Hải tặc Mũ Rơm xuất hiện...<br><br>Át chủ bài của Hải quân, Viên đá Daina - được so sánh ngang hàng với Vũ khí Cổ đại, đột nhiên bị lấy cắp! Và người đàn ông có sức mạnh kinh hoàng, cựu Đô Đốc Hải Quân 'Z' sẽ là kẻ chặn đường băng Mũ Rơm! Tổng bộ Hải Quân cuối cùng cũng tiến tới việc đối phó với âm mưu đe dọa phá huỷ các End Point (Điểm Kết Thúc) tại Tân Thế giới. Ở nơi khác, Aokiji gặp mặt băng Mũ Rơm. Và cuối cùng, Luffy và đồng đội của mình tiến lên chống lại Z và sức mạnh kinh ngạc của hắn.<br><br> Xuyên suốt thời lượng phim là những trận chiến đầy kịch tính với những hiệu ứng hình ảnh đẹp mắt am thanh sống động. Phần movie này của One piece chắc chắn sẽ không làm các fan hâm mộ bộ truyện thất vọng cũng như những phút giây thư giãn của người xem.",

    },
    {
        "id": "phim8",
        "ten": "One Piece film: Gold",
        "theLoai": "Phim hoạt hình",
        "nhaSanXuat": "Fuji Television Network, Toei Animation",
        "noiDung": "One Piece Film Gold là bộ phim điện ảnh thứ 13 của thương hiệu One Piece.<br><br> Trong bộ phim lần này, băng hải tặc Mũ Rơm sẽ phải đối đầu với Guild Tesoro, kẻ sở hữu trái ác quỷ Gold - Gold và là chủ nhân của Gran Tesoro - Thành phố giải trí nổi bằng vàng lớn nhất thế giới. Gran Tesoro là một thành phố độc lập, quy tụ hàng trăm tay chơi và hải tặc trên khắp thế giới; một nơi mà đến chính phủ cũng không thể kiểm soát. Guild Tesoro thống trị tất cả mọi thứ, thậm chí là hải tặc hay chính phủ bằng Vàng và tham vọng của hắn ngày càng lớn dần. Cán cân quyền lực của Tân thế giới bắt đầu thay đổi từ đây…",
        "thoiLuong": "120 phút",
        "namSanXuat": "2016",
        "anh": "OnePiece-G.jpg",

        "IMDb": "8.3",
        "trailer": "NmyGak3l12Y",
            "daoDien": "Hiroaki Miyamoto",
            "dienVien": "Tanaka Mayumi, Nakai Kazuya, Okamura Akemi, Yamaguchi Kappei, Hirata Hiroaki, Ōtani Ikue, Yamaguchi Yuriko, Yamaji Kazuhiro, Mitsushima Hikari, Hamada Gaku, Nanao, Kobayashi Kendo, Kitaōji Kin'ya",
            "quocGia": "Nhật Bản",
            "ngonNgu":"Tiếng Nhật",
            "review": "NỘI DUNG:<br> Có tác giả Oda Eiichiro bảo chứng về mặt chất lượng, quả nhiên One Piece Film: Gold không làm các fan phải thất vọng. Nhịp phim dồn dập, biến đổi rất uyển chuyển. Mở đầu là biết bao nhiêu phấn khích, hào hứng khi cả băng mới bắt đầu khám phá điểm đến mới. Tuy nhiên, bằng những chi tiết rất nhỏ, mặt trái của thành phố dát vàng Grantesoro dần lộ rõ. Các phân cảnh hành động cũng được trải đều trong toàn bộ thời lượng phim với quy mô càng lúc càng khốc liệt khiến khán giả không thể rời mắt khỏi màn hình. Những trường đoạn hài hước cũng được thêm vào đúng lúc đúng chỗ vừa không làm giảm độ kịch tính, hấp dẫn của One Piece Film: Gold mà còn giúp khán giả còn thời gian tạm nghỉ, tránh bị trụy tim dưới kích thích quá lớn. Tuy nhiên, sau khi phim được đẩy lên cao trào thì đoạn cuối lại diễn ra khá nhanh và vội: Các kẻ địch còn hết sức bá đạo trong một giây trước, một giây sau đã bị đo ván hoàn toàn mà không hề được giải thích hợp lí. Có lẽ chỉ cần thêm một chút giằng co, một chút logic cho kết thúc thì khán giả đã có thể cảm thấy hoàn toàn thỏa mãn sau khi xem xong One Piece Film: Gold.<br><br>Tính cách các thành viên trong băng Mũ Rơm đều được giữ nguyên như trong manga. Tuy nhiên, do dàn nhân vật khá nhiều (tính cả phe ta lẫn phe địch cũng đã lên tới 13 người) nên phim chỉ có thể tập trung khai thác một vài người. Lần này, ngoài Luffy với Gild Tesoro, lần này nhân vật đóng vai trò khá quan trọng trong One Piece Film: Gold chính “miêu tặc” Nami khi có sự xuất hiện của “đồng đội” cũ Carina. Tình bạn “yêu nhau lắm cắn nhau đau” của hai cô gái khá thú vị, vừa dễ thương vừa hài hước. Đoạn kí ức nhỏ giữa hai người cũng là đòn bẩy để tạo cao trào cho phim. Ngoài ra thì nhân vật Gild Tesoro cũng ấn tượng không kém với một quá khứ khá bi kịch, khiến người xem giận thì giận mà thương thì vẫn thương.<br><br>ÂM NHẠC VÀ HÌNH ẢNH:<br>Phần tạo hình nhân vật của hãng sản xuất Toei quả nhiên vẫn còn rất nhiều bất cập khi tỉ lệ cơ thể người, đặc biệt của các nhân vật nữ, hoàn toàn bị bóp méo! Cảm tưởng như số đo ba vòng của các cô gái trong One Piece Film: Gold không phải là 90-60-90 mà là 90-30-90 mới đúng! Tuy nhiên, bù đắp cho tạo hình thì mảng phông nền gây được ấn tượng mạnh với người xem. Cả con thuyền Grantesoro và Thousand Sunny đều được dựng bằng công nghệ 3-D nhưng lại không hề đối chọi với các nhân vật vẫn vẽ theo kiểu 2-D truyền thống. Sự tỉ mỉ trong background còn được thể hiện khi từng hạt vàng nhỏ trong tổng thể một cơn mưa vàng đều được chăm chút hết sức cẩn thận.<br><br>Phần âm thanh trong One Piece Film: Gold đóng vai trò quan trọng trong việc giữ nhiệt. Các bản nhạc nền hào hùng dũng mãnh mà tiêu biểu là Daigyakuten khiến cho những trường đoạn chiến đấu vốn đã khốc liệt lại càng khốc liệt hơn, vốn đã hào hùng lại càng hào hùng hơn. Hai ca khúc chủ đề, một là Ikari wo Kureyo do nhóm nhạc GLIM SPANKY trình bày, một là bản nhạc GOLD & JIVE ~ SILVER OCEAN của nữ nhạc sĩ Mayumi Kojima, thì ngược lại, đều mang chút âm hưởng của nhạc cổ điển, đem đến cảm giác xa hoa và sang trọng như chính tựa đề của bộ phim vậy.",

    },
    {
        "id": "phim9",
        "ten": "Cuộc đổ bộ bí ẩn (Arrival)",
        "theLoai": "Phim viễn tưởng",
        "nhaSanXuat": "21 Laps Entertainment, FilmNation Entertainment, Lava Bear Films",
        "noiDung": "Nhà ngôn ngữ học Louise Banks (Amy Adams) được chính phủ Mỹ mời đến phiên dịch thông điệp của một nhóm người hành tinh mới đến Trái đất. Cùng với nhà vật lý Ian Donnelly (Jeremy Renner), Banks giải mã được nghĩa của chúng là: “Giao vũ khí ra”. Đứng trước mối đe dọa, nhiều quốc gia chuẩn bị phát động một cuộc chiến tranh tổng lực có thể tàn phá cả Trái đất. Tuy nhiên đằng sau mọi chuyện vẫn còn nhiều bí ẩn khó lường, và chìa khóa cho vận mệnh thế giới giờ đây phụ thuộc vào những khám phá của Banks.",
        "thoiLuong": "116 phút",
        "namSanXuat": "2016",
        "anh": "vienTuong-1.jpg",

            "IMDb": "8.2",
            "trailer": "CuLT9IGupTg",
            "daoDien": "Denis Villeneuve",
            "dienVien": "Amy Adams, Jeremy Renner, Forest Whitaker, Michael Stuhlbarg, Tzi Ma",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "Nếu xem Arrival - Cuộc đổ bộ bí ẩn, với cách nhìn thời gian như là một cuộc sống có sinh, có tử... có khởi đầu, có kết thúc... có Alpha và Omega, bạn sẽ bị lạc giữa một mê cung không bao giờ có đường ra. Đơn giản vì điều kiện để tìm ra toàn bộ ý niệm của Arrival là bác bỏ hoàn toàn sự tồn tại của thời gian.<br><br>Đối với những người có thể hiểu bộ phim, sự thành công của Arrival nợ ơn sinh thành với đạo diễn Denis Villeneuve và nhà văn Ted Chiang, tác giả cuốn tiểu thuyết Story of Your Life - cuốn sách mà chính Arrival dựa theo. Câu chuyện xoay quanh một nhà ngôn ngữ học mang tên Louise Banks với nhiệm vụ dịch lại thông điệp của Hectapod - chủng tộc ngoài hành tinh bất ngờ đáp xuống Trái Đất. Trong khi thế giới ngoài kia đang phát điên vì sự hiện diện của một trí thông minh ngoài vũ trụ và quân đội khắp nơi chuẩn bị tấn công vào phi thuyền, Louise lại cố gắng giao tiếp với họ theo một cách hòa bình.. trước khi mọi thứ nhấn chìm trong biển máu.<br><br>Là một tác phẩm thuộc dòng khoa học viễn tưởng nên Arrival chỉ có thể thực sự gây ấn tượng nếu các yếu tố kỹ thuật như hình ảnh, kỹ xảo, và thiết kế bối cảnh được quan tâm thỏa đáng.<br><br>Với sự cộng tác của nhà quay phim Bradford Young, đạo diễn Denis Villeneuve tạo dựng cho tác phẩm viễn tưởng đầu tiên sự nghiệp phần nhìn đơn giản, gần gũi với thực tại, nhưng vẫn pha trộn tinh tế những chi tiết vừa đậm chất giả tưởng về người ngoài hành tinh, vừa mang ý nghĩa ẩn dụ về triết lý nhân sinh và quy luật nhân quả cuộc đời.<br><br>Tại Oscar 2017, Arrival nhận tổng cộng 8 đề cử cho Phim truyện, Đạo diễn, Kịch bản chuyển thể, Quay phim, Dựng phim, Thiết kế sản xuất, Hòa âm và Dàn dựng âm thanh xuất sắc.",
    },
    {
        "id": "phim10",
        "ten": "Hố đen tử thần (Interstellar)",
        "theLoai": "Phim viễn tưởng",
        "nhaSanXuat": "Paramount Pictures, Warner Bros., Legendary Entertainment",
        "noiDung": "Trong tương lai, các nguồn tài nguyên thiên nhiên trên trái đất dần cạn kiệt dẫn loài người tới bờ của sự huỷ diệt, thức ăn khan hiếm và NASA thì không còn nữa.<br><br> Cooper, một nông dân trước đây từng là kỹ sư và phi công thử nghiệm của NASA, sống cùng với bố vợ, con trai và con gái 10 tuổi Murphy. Murphy tin rằng, căn phòng của mình bị ám bởi một thế lực siêu nhiên đang cố gắng liên lạc với mình. Murphy và cha (Cooper) phát hiện ra rằng thế lực siêu nhiên đó là một dạng thông minh chưa được biết đến đang gửi các thông điệp đã được mã hoá cho mình thông qua sóng hấp dẫn.<br><br>Một đoàn thám hiểm vũ trụ sử dụng một hố đen mới được khám phá để du hành xuyên không gian đến những vì sao xa xôi và tìm kiếm hy vọng cho loài người.<br><br>“Interstellar” là biên niên ký về cuộc phiêu lưu vĩ đại của một nhóm các nhà thám hiểm sử dụng khám phá mới về lỗ đen vũ trụ để vượt qua các giới hạn thông thường trong du hành không gian, chinh phục khoảng không mênh mông trên một chuyến hành trình xuyên dải ngân hà...",
        "thoiLuong": "169 phút",
        "namSanXuat": "2014",
        "anh": "vienTuong-2.jpg",

        "IMDb": "8.6",
        "trailer": "QqSp_dwslro",
            "daoDien": "Christopher Nolan",
            "dienVien": "Matthew McConaughey, Anne Hathaway, Jessica Chastain , Blake Lively, Bill Irwin,Ellen Burstyn, Michael Caine",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "Xem phim này tại một trong những suất cuối của Interstellar và hoàn toàn câm nín vì sự hấp dẫn của nó. Tác phẩm này là thứ truyền cảm hứng và xúc động nhất mà mình từng được xem trong năm 2014.<br><br>CỐT TRUYỆN:<br>Cooper từng tham gia để trở thành phi công của NASA. Nhưng rồi một tai nạn trong lúc diễn tập đã khiến anh thất bại trong việc theo đuổi giấc mơ của mình. Thế là anh trở thành một nông dân và một ông bố độc thân với 2 đứa con.Đứa con gái út của anh, Murph , thừa hưởng từ anh trí tuệ và sự tò mò dành cho thế giới này. Và bằng một sự kiện tình cờ, hai cha con anh đã phát hiện ra tọa độ của cơ quan NASA (nay đã hoạt động bí mật).Những sự kiện liên tiếp dẫn đến việc Cooper (Matthew McConaughey) chấp nhận bay vào vũ trụ để tìm ra ngôi nhà mới cho nhân loại với lời hứa “Bố sẽ trở về dành cho con gái anh.<br><br>ÂM NHẠC:<br>Âm nhạc trong Interstellar khiến người ta thốt lên “ Đúng là cảm giác trong vũ trụ” dù rằng chẳng mấy ai trong chúng ta từng bay vào vũ trụ. Sử dụng đàn organ nhà thờ, Nolan đã gợi lên cảm giác của một âm vô cùng vang dội nhưng dần dần biến mất trong không gian. Đó cũng là cảm giác của những nhân vật trong phim: họ tan biến trong khoảng không của vũ trụ, như một hạt cát trong sa mạc. Mọi cảm xúc dù mạnh mẽ như tiếng trống dồn, hay day dứt như tiếng đàn khi bị đặt vào trong vũ trụ và trước hố đen quyền năng, đều biến mất một cách nhẹ tâng. Những “nặng”, “nhẹ” vô hình đó đều được sứ giả âm nhạc truyền tải hoàn hảo.<br><br>HÌNH ẢNH:<br>Mình chưa xem “Gravity” đoạt Oscar 2013. NHưng mình khẳng định “Interstellar” không hế thua kém “Gravity”. Bởi vì “Interstellar” không chỉ có sự hung vĩ của thiên nhiên, sự huyền bí của vũ trụ mà còn đây sự “mộng mơ” trong những tác phẩm của Nolan. Và hình ảnh của nó dĩ nhiên còn mang đầy tính ẩn dụ.Đẹp về vẻ ngoài và tràn đầy thông điệp, hình ảnh trong “Interstellar” khiến người xem phải ngưng đọng hơi thở của mình.<br><br>Kết luận: Christopher Nolan vẫn rất cao tay trong việc tạo ra những tác phẩm “truyền cảm hứng”. Trong 1 Gotham tha hóa, ông truyền cảm hứng về công lý, đức hy sinh. Trong 1 trái đất chỉ còn lại cát bụi, ông tạo ra niềm tin về sự tái sinh, sự cứu rỗi dành cho những con người biết tin vào điều tốt đẹp.",
    },
    {
        "id": "phim11",
        "ten": "The Karate Kid",
        "theLoai": "Phim hành động",
        "nhaSanXuat": "Columbia Pictures, China Film Group,",
        "noiDung": "Câu bé Dre Parker, 12 tuổi theo mẹ di chuyển từ thành phố Detroit, Mỹ sang Bắc Kinh, Trung Quốc. Tại đây, ngỡ ngàng với cuộc sống mới, khác biệt về ngôn ngữ, Dre vô tình gây sự đánh nhau với những học sinh giỏi kungfu Trung Quốc cùng trường. Để lấy lại danh dự và cũng để chinh phục cô bạn gái Mỹ Anh xinh đẹp, Dre quyết tâm học võ. Và vị sư phụ chính là ông thợ điện bí ẩn sống cùng khu phố.",
        "thoiLuong": "140 phút",
        "namSanXuat": "2010",
        "anh": "hanhDong-1.jpg",
        "IMDb": "6.2",
        "trailer": "XY8amUImEu0",
            "daoDien": "Harald Zwart",
            "dienVien": "Jaden Smith, Thành Long",
            "quocGia": "Mỹ, Trung Quốc",
            "ngonNgu":"Tiếng Anh, tiếng Trung",
            "review": "phiên bản đầu tiên của The Karate Kid (1984) ra mắt khán giả và nhanh chóng đạt được thành công rực rỡ với doanh thu hơn 90 triệu USD và một đề cử Oscar diễn viên phụ xuất sắc nhất cho sư phụ Pat Morita. Không chỉ là một bộ phim võ thuật giải trí đơn thuần, The Karate Kid (1984) đề cao tinh thần thượng võ và là bài học về tình bạn của lứa tuổi học trò. Ba phần tiếp theo của phim cũng gặt hái được thành công không kém, đặc biệt phần The Next Karate Kid có cả sự góp mặt của nữ diễn viên Hilary Swank từng đoạt giải Oscar. Hiện nay The Karate Kid (1984) vẫn nằm trong danh sách 50 phim hay nhất về đề tài thể thao học đường của trang web giải trí EW entertainment.<br><br>Năm 2009, khi ngôi sao điện ảnh võ thuật Thành Long bắt tay vào làm lại bộ phim The Karate Kid 2010 nhiều khán giả đã lo lắng phiên bản mới khó vượt qua được thành công của phiên bản gốc, cũng như Thành Long không thể thay thế huyền thoại của sư phụ Miyagi (Pat Morita). Nhưng ngay khi chiếu ra mắt khán giả trên toàn thế giới, những lo âu đã hoàn toàn biến mất thay vào đó là sự đón nhận nồng nhiệt và những lời khen không ngớt. Đó cũng là lý do mà bộ phim đã đứng đầu bảng xếp hạng Box Office ngay tuần đầu tiên ra mắt với doanh thu 56 triệu USD.<br><br>Một đặc điểm mà bất kỳ khán giả nào khi xem phim của Thành Long đều chờ đợi đó là những chi tiết tiếu lâm, những tràng cười không ngừng nghỉ. Đạo diễn Harald Zwart, người từng rất thành công với Agent Cody Banks (2003) đã không làm khán giả phải thất vọng khi chịu trách nhiệm đạo diễn The Karate Kid. Tíếng cười trên hàng ghế khán giả tuôn trào không ngừng kể từ đầu phim cho đến tận cuối phim, từ sân luyện võ lên cả sàn đấu. Những chi tiết hài nhẹ nhàng và rất có duyên  như bài học luyện nói tiếng Trung cho đến một lá thư xin phép, hay một câu chuyện chỉ xuất phát từ cái áo khoác của mẹ...<br><br>Phim không chỉ có hài hước, mà còn có nhiều bài học sâu sắc về tình người và cách sống tràn đầy tình nghĩa giữa con người khác tiếng nói, khác màu da với nhau. Hình ảnh 2 thầy trò cùng trò chuyện trong xe vô cùng đẹp. Không chỉ cậu bé Dre Parker nhận ra rằng thắng thua không quan trọng, mà câu cũng giúp sự phụ Han đứng lên sau nỗi đau của quá khứ. Không ai không một lần thất bại, quan trọng là sau đó họ chấp nhận nó như thế nào, đứng lên hay gục ngã mãi mãi. Đây cũng chính là thông điệp chung của cả series The Karate Kid.",

    },
    {
        "id": "phim12",
        "ten": "Kẻ săn người (Hitman)",
        "theLoai": "Phim hành động",
        "nhaSanXuat": "Twentieth Century Fox Film Corporation, EuropaCorp, Anka Film",
        "noiDung": "rong bộ vest đen lịch thiệp, với gương mặt pha nét Á Đông lạnh lùng, hắn khiến những con mồi của mình phải chùn bước, run sợ mà nạp mạng cho hắn. Hắn là một Sát thủ chuyên nghiệp, được huấn luyện với tất cả những ngón nghề cùng sự khôn ngoan để lấy mạng kẻ khác, chẳng ai biết tên thật của hắn, chỉ biết hắn được gọi là 47, đó là 2 con số được in cùng 1 thanh mã vạch như trên các gói hàng đằng sau cổ và dưới cái đầu trọc lóc đến lạnh lẽo của hắn.<br><br>Thợ săn trở thành con mồi khi hắn bị cả Interpol cùng quân đội Nga truy lùng khắp Đông Âu sau khi thực hiện 1 hợp đồng ám sát nhưng nguy hiểm lớn nhất đang rình rập hắn không phải từ những họng súng truy lùng kia mà là từ một ả đàn bà, kẻ đã làm con tim băng giá của 1 gã Sát thủ bắt đầu tan chảy...<br><br>Dựa theo nhân vật trong loạt game video bán chạy nhất và từng giành nhiều giải thưởng, Hitman là câu chuyện về sát thủ được biết đến dưới bí danh Đặc vụ 47. Nhưng cho dù là kẻ sát thủ máu lạnh chưa một lần chùng tay trước nạn nhân, lần này bí số 47 lại xiêu lòng vì một bóng hồng huyền bí đến từ nước Nga.",
        "thoiLuong": "100 phút",
        "namSanXuat": "2007",
        "anh": "hitman.jpg",
        "IMDb": "6.3",
        "trailer": "u9KUbeac1ak",
            "daoDien": "Xavier Gens",
            "dienVien": "Timothy Olyphant, Dougray Scott, Robert Knepper, Olga Kurylenko",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "Bắt đầu từ tựa game kinh điển Năm 2000, hãng game Đan Mạch còn non trẻ IO Interative ra mắt tựa game đầu tay, Hitman: Codename 47. Game thuộc thể loại hành động lét lút, người chơi vào vai một tay sát thủ thực hiện các nhiệm vụ ám sát ở nhiều nơi trên thế giới. Vượt hơn sự mong đợi của nhà sản xuất, Hitman được đón nhận nhiệt liệt từ giới game thủ lẫn phê bình, nhanh chóng trở thành kinh điển đối với thể loại hành động.<br><br>Điều đáng tiếc nhất ở bộ phim này đó là sự ra đi của tài tử Paul Walker. Người hùng của loạt Fast And Furious đã đồng ý đảm nhiệm vai chính của phim, nhưng không may qua đời trong tai nạn xe hơi cuối năm 2013. Rupert Friend được lựa chọn thay thế. Agent 47 cũng là bộ phim đầu tay của đạo diễn người Đức Aleksander Bach.<br><br>Bộ phim này có sự hậu thuẫn lớn đến từ phiên bản game sẽ ra mắt vào tháng 12 năm nay, được giới thiệu kèm tại các hội chợ game danh tiếng như E3 vừa qua. Các nhà sản xuất quyết định sẽ chiều lòng fan hâm mộ bằng cả hai phiên bản phim và game trong cùng một năm.<br><br>Ngoài ra, những fan “ruột” của game sẽ gặp lại những nhân vật quen thuộc đã xuất hiện cùng họ trên màn hình điện tử. Đó là gã trùm The Albino (Gã Bạch Tạng), hay được gọi là Mark Parchezzi III trong game. Đây là nhân vật tương đồng với Hitman, với các khả năng siêu việt tương tự. Nhưng hắn không quan tâm đến việc sát thủ, mục đích duy nhất chỉ là theo đuổi và tiêu diệt Hitman",

    },
    {
        "id": "phim13",
        "ten": "Alita: thiên thần chiến binh",
        "theLoai": "Phim hành động, Phim viễn tưởng",
        "nhaSanXuat": "Twentieth Century Fox, Lightstorm Entertainment, Troublemaker Studios",
        "noiDung": "Alita: Thiên thần chiến binh là câu chuyện về Alita – người máy sinh học duy nhất còn sót lại sau cuộc chiến cách đây 300 năm trước. Ba thế kỷ sau Alita lưu lạc tại bãi phế liệu với bộ não còn nguyên vẹn và trái tim được cấu tạo đặc biệt đã thất truyền rất rất nhiều năm qua. Alita được tiến sĩ Dyson Ido nhặt về và phục hồi thân thể với những thiết bị cơ khí, cái tên Alita cũng là ông đặt cho cô theo tên người con gái đã mất của ông.<br><br>Alita được ví như một thần chết đến từ địa ngục vì những khả năng vượt qua mọi giới hạn mà cô sở hữu. Cô được tìm thấy bởi Tiến sĩ Ido và không thể nhớ mình là ai hay từ đâu tới. Để có thể tìm ra sự thật, Atila phải dấn thân vào những cuộc chiến đấu nảy lửa.",
        "thoiLuong": "122 phút",
        "namSanXuat": "2019",
        "anh": "alita.jpg",

        "IMDb": "7.5",
        "trailer": "hpLUO424uHg",
            "daoDien": "Robert Rodriguez",
            "dienVien": "Rosa Salazar, Christoph Waltz, Jennifer Connelly, Mahershala Ali, Ed Skrein, Jackie Earle Haley",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "Tài năng biên kịch của James Cameron và đạo diễn Robert Rodrigue đã mang đến cho khán giả một cô người máy vô tri vô giác với trí nhớ hoàn toàn trống rỗng. Alita hay thực sự là cô robot số 99 đưa khán giả khám phá một thế giới hoàn toàn mới không quá xa lạ nhưng cũng không hề quen thuộc.<br><br>DIỄN XUẤT:<br>Dàn diễn viên góp mặt trong Alita: Thiên thần chiến binh đều là những gương mặt tài năng của nền điện ảnh thế giới. Sự có mặt của họ đóng vai trò quan trọng trong việc mang đến thành công cho bộ phim.<br>Vai nữ chính Alita được giao cho diễn viên trẻ Rosa Salazar và cô đã khiến khán giả phải ngã mũ thán phục bởi những gì bản thân mình đã thể hiện. Rosa đã phải trang bị những phụ kiện đặc biệt trong suốt thời gian quay phim để khắc họa chân thực nhất từng hành động của nhân vật, từ đó để dựng thành bản 3D. Từng cái nhíu mày hay mím môi đều được cô diễn tả rất xuất sắc và được mô phỏng quá đỗi chính xác lên màn ảnh.<br><br>ÂM THANH, HÌNH ẢNH:<br>Kỹ xảo của bộ phim thực sự quá ấn tượng, đặc biệt trong bản 3D hình ảnh nổi được xử lý vô cùng tinh tế và đẹp mắt. Những phân cảnh hành động không quá nhiều nhưng đủ “ép phê”, bạn sẽ nhiều phen phải chợp mắt sợ hãi bởi vì có cảm giác như sợi xích sắt đâm thẳng vào mặt bản, cũng phải xuýt xoa khen ngợi bởi những màn đấu võ chân thực không kém gì người thật đóng. James Cameron đã từng chi sẻ rằng: ông dồn tất cả kinh nghiệm từ những tác phẩm điện ảnh trước đó để mang đến cho khán giả một bộ phim có sự chân thực và động phá về mặt hình ảnh, kỹ xảo. Tất nhiên ông và những cộng sự của mình đã làm được điều đó, khiến người xem không thể rời mắt khỏi màn hình dù chỉ một tích tắc.<br><br>Âm thanh và tiếng động trong Alita: Thiên thần chiến binh cũng xử lý rất tốt. Trong phim không hề có bất cứ tiếng động dư thừa nào, mọi tiếng động phát ra đều có mục đích đưa cảm xúc của khán giả lên cao trào. Kết hợp với phần âm nhạc được hòa trộn khéo léo vào nội dung phim càng góp phần giúp bộ phim trở nên hấp dẫn, thú vị và ấn tượng hơn.",

    },
    {
        "id": "phim14",
        "ten": "Vệ binh dải ngân hà",
        "theLoai": "Phim hành động, Phim viễn tưởng, Phim hài",
        "nhaSanXuat": "Marvel Enterprises",
        "noiDung": "Phim kể về Ronan, một tên bạo chúa muốn tiêu diệt nền văn minh của con người trong hành tinh Xandar. Để làm việc đó, hắn phải có được một món là Năng lượng vô cực, xuất hiện trong phim với dạng một viên ngọc màu tím. Để ngăn chặn việc này, nhóm năm người vô tình được sắp xếp để chung vai sát cánh chiến đấu chống lại Ronan. Nhóm này bao gồm tên trộm Peter Quill, nữ sát thủ Gamora, gã bự con hơi điên Drax , con chồn xảo quyệt Rocket và một linh hồn cây có hình dạng như người tên Groot. Phim có sự tham gia diễn xuất của Karen Gillan, Bradley Cooper, Zoe Saldana… và sự chỉ đạo của đạo diễn James Gunn",
        "thoiLuong": "100 phút",
        "namSanXuat": "2014",
        "anh": "veBinh.jpg",

        "IMDb": "8.8",
        "trailer": "xh2lgzlwQ30",
            "daoDien": "James Gunn",
            "dienVien": "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel, Bradley Cooper, Lee Pace, Michael Rooker, Karen Gillan",
            "quocGia": "MỸ",
            "ngonNgu":"Tiếng Anh",
            "review": "Nội dung phim “Guardians of the Galaxy” không quá phức tạp, ai coi cũng hiểu. Điểm cộng là nhịp phim rất nhanh, các tình tiết diễn ra liên tục khiến người xem không cảm thấy nhàm chán, mệt mỏi như khi coi phần mở đầu hơi lê thê của các bom tấn khác như “Thor” hay “Iron Man”. Một nguyên nhân khác khiến phim coi “đã” chính là các tình huống và lời thoại hài hước một cách cực kỳ thông minh, tính cách của nhân vật cũng hài hước, hoạt ngôn, khiến người xem khó có thể lơ đãng.<br><br>Bên cạnh sự hài hước xuyên suốt, “Guardians of the Galaxy” vẫn để lại những khoảng lặng đủ cần thiết cho người xem cần sự suy ngẫm. Có những cảnh tưởng chừng rất nhỏ nhưng lại khiến người xem thấy ấm áp, đẹp và dễ ghi nhớ, như khi nhân vật người cây Groot đến một vùng mỏ, có những đứa trẻ ăn xin chạy tới, cậu ta chìa tay, để một bông hoa nở trên tay mình và đem tặng cô bé. Một chi tiết đẹp và nhiều tính nhân văn. <br><br>HÌNH ẢNH, ÂM THANH:<br>Hình ảnh và âm thanh của “Guardians of the Galaxy” cũng là hai thứ đáng cho người ta bỏ tiền mua vé. Đã nghe tên Marvel thì coi như chắc chắn có những màn đại chiến ngân hà siêu kinh điển. Một đoạn có thể làm bạn nổi da gà khi coi là cảnh hàng vạn phi thuyền chiến đấu hình ngôi sao của Xandar kết hợp thành mạng lưới để bảo vệ thành phố, nhìn rất sướng mắt. Nhạc trong phim có giai điệu dễ nghe, theo phong cách thập niên 60 – 70 với những bản jazz pha trộn twist khiến người nghe muốn lắc lư theo. <br><br>Nhìn chung, với thang điểm 10 thì “Guardians of the Galaxy” xứng đáng được 9 điểm, vì tính giải trí cực kỳ tuyệt vời của nó dành cho người xem. Chẳng có lý do gì để bạn không mua vé, dắt người yêu (nếu có) ra rạp và thưởng thức bộ phim này trong dịp cuối tuần.",

    },
    {
        "id": "phim15",
        "ten": "Chú hề ma quái (IT)",
        "theLoai": "Phim kinh dị",
        "nhaSanXuat": "New Line Cinema, KatzSmith Productions, Lin Pictures",
        "noiDung": "IT - Chú Hề Ma Quái xoay quanh tình bạn thời thơ ấu bền chặt của 7 đứa trẻ trong nhóm The Loser. Những cậu bé, cô bé hồn nhiên ấy đang bị ám ảnh bởi một thế lực tà ác trong hình hài chú hề. Trailer tập trung lột tả sự ghê rợn của gã hề Pennywise. Hắn ta đã mang đến sự chết chóc cho thị trấn Derry trong hàng chục năm qua. Hắn có mặt ở khắp mọi nơi và liên tục khủng bố tinh thần lũ trẻ. Hắn “chơi đùa” trên nỗi sợ hãi của những đứa trẻ.<br><br>Lấy bối cảnh thị trấn Derry cũ kỹ những năm 80, IT dựng nên một thế giới vừa xa lạ vừa quen thuộc. Dù vùng đất có vẻ ngoài bình yên này 27 năm mới gặp tai họa một lần nhưng dường như tất cả đã bị bao trùm bởi bầu không khí bức bối từ rất lâu rồi.<br><br>Bộ phim mở đầu bằng một trận mưa lớn, cậu bé Georgie mang con thuyền anh trai xếp cho mình chạy dọc các con phố để rồi mất tích. Từ khoảnh khắc ấy, các phân đoạn còn lại đều diễn ra dưới tiết trời nắng đẹp. Thế nhưng, ánh nắng vàng rực rỡ không thể xua đi bầu không khí ẩm mốc, tràn ngập mùi máu tươi với những tội ác đang âm thầm diễn ra khắp các ngóc ngách trong thị trấn. Không chỉ là tội ác do tên hề ngoài hành tinh Pennywise gây ra, mà còn nhiều cá nhân khác, khi con người tổn thương con người và những đứa trẻ trở thành nạn nhân vì sự vô tâm của người lớn.",
        "thoiLuong": "135 phút",
        "namSanXuat": "2017",
        "anh": "IT.jpg",

            "IMDb": "7.9",
            "trailer": "EvSgbfzKWdg",
            "daoDien": "Andy Muschietti",
            "dienVien": "Jaeden Lieberher, Sophia Lillis, Bill Skarsgård, Jeremy Ray Taylor",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "IT có cốt truyện hơi thiếu cân bằng khi khá dài dòng giai đoạn đầu nhưng diễn biến quá nhanh vào những phút cuối. Tuy nhiên, vì đây là phần đầu tiên trong một series phim, việc mất nhiều thời gian giới thiệu nhân vật dễ hiểu. Điểm đáng khen của IT nằm ở sự thông minh khi đưa những câu thoại hài hước vào đúng lúc đúng chỗ. Người xem cười lên đó rồi lại sợ hãi ngay lập tức. Ma quỷ các phim khác thường xuất hiện trong những khung cảnh tối tăm còn ở IT, gã hề Pennywise xuất hiện ngay cả ban ngày dưới mặt trời chói chang.<br><br>Thành công của IT không thể bỏ qua yếu tố casting khi đã chọn được một dàn diễn viên xuất sắc. Các diễn viên nhí đều rất hợp vai. Đặc biệt là nhóm bảy đứa trẻ nhận nhiệm vụ tiêu diệt Pennywise độc ác.<br><br>IT cũng thành công giới thiệu gương mặt mỹ nhân nhí - Sophia Lillis. Sở hữu nét đẹp điện ảnh vô cùng ấn tượng, Bervely Mash thu hút ánh nhìn người xem ngay từ cảnh đầu tiên xuất hiện. Thông minh, dịu dàng, tinh tế và vô cùng can đảm, Bervely khiến cho khán giả cũng như những cậu bạn cùng nhóm không thể không yêu thích. Hoàn cảnh nhân vật bi đát giúp Sophia có cơ hội thể hiện những cảnh diễn nội tâm độ khó cao.<br><br>Với đôi má hồng hồng, dáng vẻ tròn xoe, bộ óc của nhóm – Ben Hanscom giành được rất nhiều tình cảm. Cậu nhóc Jeremy Ray Taylor đóng phim từ năm 2011. Finn Wolfhard, Chosen Jacobs, Jack Dylan Grazer và Wyatt Oleff mỗi người một vẻ đều hoàn thành xuất sắc nhiệm vụ. Các cậu bé diễn xuất đơn giản, tự nhiên như thể mình chính là những nhân vật, sống ở thời đại ấy.  Đặc biệt, Jackson Robert Scott vai Georgie Denbrough cũng gây bất ngờ lớn. Vẻ ngoài đáng yêu cùng chất giọng ngọt ngào nũng nịu khiến người xem vừa đau xót đoạn đầu phim vừa sợ hãi trong những phân đoạn sau khi Georgie bé nhỏ đã trở thành một đứa trẻ “lơ lửng”.",

    },
    {
        "id": "phim16",
        "ten": "Búp bệ ma ám (Annabelle)",
        "theLoai": "Phim kinh dị",
        "nhaSanXuat": "New Line Cinema, Atomic Monster, Evergreen Media Group",
        "noiDung": "Annabelle là câu chuyện về nguồn gốc của búp bê quỷ ám. Đi sâu vào bộ phim lần này Annabelle xuất hiện tại một gia đình vợ chồng trẻ. Món quà John tặng vợ mình nhân dịp sinh nhật và chuyển tói nhà mới chính là con búp bê Annabelle. Vào một đêm định mệnh, nhà của họ bị hai kẻ tâm thần đột nhập vào. Kể từ sau sự kiện kinh hoàng, nhiều hiện tượng kì quái bắt đầu xảy ra trong nhà và đều liên quan tới búp bê Annabelle…<br><br>Dù được xem là phần tiếp của Annabelle 2014 không mấy thành công nhưng thật ra, Annabelle: Creation mới chính là phần đầu và thậm chí nó còn là sự bắt đầu của toàn bộ vũ trụ Phim kinh dị Conjuring của James Wan khi đã cho thấy một sự liên kết với các bộ phim trước đó như The Conjuring, The Conjuring 2 và Lights Out.",
        "thoiLuong": "99 phút",
        "namSanXuat": "2014",
        "anh": "annabelle.jpg",

            "IMDb": "5.4",
            "trailer": "Y7lixOKk6sg",
            "daoDien": "John R. Leonetti",
            "dienVien": "Annabelle Wallis, Ward Horton, Alfre Woodard",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "Với phần đầu tiên ra mắt vào năm 2014, sau ngày ra mắt của The Conjuring đúng một năm, đáng lẽ đó sẽ là một bộ phim hứa hẹn đầy thành công vì khán giả đã bị ấn tượng mạnh với tạo hình và câu chuyện rùng rợn về quá khứ của con búp bê hắc ám Annabelle chỉ từ một đoạn nhá hàng ngắn trong The Conjuring. Nhưng không, Annabelle đã vấp phải nhiều đánh giá chê bai từ các nhà phê bình lẫn khán giả. Bộ phim đã tạo ra một sự thất vọng to lớn cho rất nhiều người sau khi đã mãn nhãn với màn trừ tà của cặp vợ chồng Edward -Lorraine và họ mong chờ nó sẽ còn làm được nhiều hơn thế. Nhưng giờ đây, các nhà sản xuất đã chuộc lỗi bằng cách giải thích về nguồn gốc cũng như sức mạnh tà ác nào đã đem đến cho con búp bê sức mạnh to lớn đến như thế với Annabelle:Creation.<br><br>Annabelle: Creation thật sự đã thành công hơn rất nhiều so với phần trước đó. Với kịch bản chặt chẽ, logic hơn, những màn dọa ma khiến người xem không hề dễ dàng đoán trước và đáng giá nhất chính là hai mối liên kết rất rõ với Valak trong The Conjuring 2 và con quỷ trong Lights Out - Diana. Người xem tỏ ra rất thích thú khi nhận ra sự xuất hiện của hai thế lực ma quỷ đã từng làm mưa làm gió trên khắp các trang mạng xã hội. Đối với Valak thì đơn giản chỉ là một easter-egg nhưng đối với Diana thì nó còn là một cái gì đó hơn nữa. Diana xuất hiện trong cảnh cuối khi Carol bị dồn vào căn nhà kho nơi chứa con bù nhìn rơm mà trước đó cô bé đã đùa giỡn lên nó. Tại đây, con bù nhìn dần biến hình thành một sinh vật mang màu đen kịt và bắt đầu dập tắt hết tất cả ánh sáng xung quanh nạn nhân. Đây là đặc trưng rõ ràng nhất của Ma Tắt Đèn. Nhưng tại sao nó lại xuất hiện đúng ngay trong căn nhà nơi chứa linh hồn tà ác đang ám vào con búp bê? Giữa Diana và Annablle có mối quan hệ nào hay có phải chính Annabelle đã triệu hồi con quỷ này lên không? Vì qua lời kể của bà Mullins, linh hồn mà vợ chồng bà tưởng là đứa con gái bé bỏng của mình lại thực ra chính là một ác linh. Thực thể này được sinh ra vì sự thương tiếc đứa con gái Bee của vợ chồng bà mà đã cầu xin mọi thế lực để có thể gặp lại dù chỉ là qua những tín hiệu nhỏ bé. Nhưng qua thời gian, thực thể này dần hiện rõ bản chất là một con quỷ và trở nên ngày càng kinh khủng hơn.<br><br>Diễn xuất của các diễn viên tương đối ổn, đặc biệt là hai nhân vật chính là hai cô bé Talitha Bateman và  Lulu Wilson. Talitha trong vai Jenice đã lột tả được hình ảnh một cô bé với tâm hồn yếu ớt dễ dàng bị dẫn dụ và sau đó lại là một khuôn mặt rõ ác của một thân xác đã bị bóng tối chiếm hữu. Ngược lại chính là hình ảnh cô bé gan lì và rất mạnh mẽ Linda của Lulu Wilson. Những biểu cảm trên gương mặt của Lulu cho người xem thấy rằng dù là đang rất sợ vì tử thần đang theo sát sau lưng như vẫn tỏ ra rất cứng rắn.<br><br>Nhìn chung Annabelle: Creation là bộ phim rất đáng xem đối với các fan của thể loại kinh dị “đau tim” này và đối với các fan của Jame Wan thì đây sẽ là một khởi đầu rất tốt cho một loạt các dự án đầy hứa hẹn sau này của “Conjuringverse”.",

    },
    {
        "id": "phim17",
        "ten": "Ám ảnh kinh hoàng (The Conjuring)",
        "theLoai": "Phim kinh dị",
        "nhaSanXuat": "New Line Cinema",
        "noiDung": "Lấy bối cảnh năm 1971, phim The Conjuring kể về câu chuyện của Ed và Lorraine Warren là một trong những người chuyên điều tra về các hiện tượng siêu nhiên nổi tiếng vào thế kỉ 20.<br><br> Một gia đình bị ma ám và liên tục bị khủng bố bởi một bóng ma kinh dị, gia đình này đã cầu xin sự giúp đỡ từ cặp đôi Warren. Tất nhiên, đây là nghề của họ nên Warren nhanh chóng nhận lời giúp đỡ. Tuy nhiên họ lại không hề biết rằng chính sự gật đầu này đã dẫn họ tiếp xúc với những thế lực siêu nhiên kì quái và trở thành một trong những vụ đáng sợ nhất mà họ từng gặp trong đời.",
        "thoiLuong": "112 phút",
        "namSanXuat": "2013",
        "anh": "phimMa.jpg",

            "IMDb": "7.6",
            "trailer": "XfFww7kqjDk",
            "daoDien": "James Wan",
            "dienVien": "Patrick Wilson, Vera Farmiga, Ron Livingston, Lili Taylor",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "Phim Ám Ảnh Kinh Hoàng đưa chúng ta về năm 1971, phim kể về câu chuyện của Ed và Lorraine Warren là 1 trong những người chuyên điều tra về các hiện tượng siêu nhiên nổi tiếng vào thế kỉ 20. Bộ phim nói về 1 gia đình bị ma ám và liên tục bị khủng bố bởi 1 bóng ma kinh dị. Gia đình này đã cầu xin sự giúp đỡ từ cặp đôi Warren. Đây là nghề của họ nên Warren nhanh chóng nhận lời giúp đỡ. Tuy nhiên họ không hề biết chính sự gật đầu này đã dẫn họ tiếp xúc với những thế lực siêu nhiên kì quái và trở thành 1 trong những vụ đáng sợ nhất mà họ từng gặp trong đời. The Conjuring khá giống với tác phẩm kinh điển The Exorcist và The Amity ville Horror cùng dàn diễn viên không “bom tấn” nhưng được tờ Variety ca ngợi “chạm đến sự đau xót và chiều sâu”. Trong trailer của The Conjuring người xem có thể hình dung câu chuyện khá ám ảnh với những sự việc kinh hoàng xảy ra trong gia đình Carolyn và Roger Parren ngay trước mắt 2 nhà điều tra. Bản thân Ed và Lorraine cũng gặp phải nguy hiểm",

    },
    {
        "id": "phim18",
        "ten": "3 chàng ngốc",
        "theLoai": "Phim hài",
        "nhaSanXuat": "Vinod Chopra Productions",
        "noiDung": "Bộ phim kể về tình bạn của ba anh chàng Farhan, Raju và Rancho từ khi họ còn là sinh viên đến khi trưởng thành. Trong thời gian ngồi trên giảng đường, Rancho đã có ảnh hưởng rất lớn đến cuộc sống, tương lai của Farhan và Raju. Sau khi ra trường, Rancho đột nhiên biến mất. 10 năm sau, khi tìm được manh mối về nơi sinh sống của cậu bạn thân năm xưa, Farhan và Raju quyết định lên đường tìm Rancho...",
        "thoiLuong": "170 phút",
        "namSanXuat": "2009",
        "anh": "3idiots.jpg",

            "IMDb": "8.4",
            "trailer": "8YGP5DSKPWU",
            "daoDien": "Rajkumar Hirani",
            "dienVien": "Aamir Khan, R. Madhavan, Sharman Joshi, Kareena Kapoor, Boman Irani, Omi Vaidya",
            "quocGia": "Ấn Độ",
            "ngonNgu":"Tiếng Hindi",
            "review": "Nếu bạn đang bắt đầu những năm tháng ngồi trên giảng đường, bạn nên xem 3 Idiots. Nếu bạn đã trải qua giai đoạn này, hãy chuẩn bị cười nắc nẻ rồi lại khóc nức nở khi thấy lại mình trong bộ phim này. Và nếu bạn làm trong ngành giáo dục, bạn cần phải xem bộ phim này để thấy được những giá trị chân chính trong ngành của mình.<br><br>Bộ phim được kể từ hồi ức của anh chàng Farhan – anh chàng từ thuở được sinh ra đời, và vì mang giới tính nam, anh đã được cha mình “đóng mác” ngay từ khi còn chưa biết gì rằng anh sẽ trở thành một kĩ sư. Con đường mà Farhan sẽ đi đã được “đóng đinh” như thế, dù rằng anh vẫn say mê chụp mọi hình ảnh trên con đường anh đi, vẫn lặng lẽ chấp nhận những con điểm thấp, vẫn vô tư đi tiếp con đường mà anh không biết sẽ dẫn đến đâu.            <br><br>Mạch cảm xúc của phim được dẫn dắt theo một cách rất lạ, thậm chí đột ngột, nhưng chạm được vào trái tim người xem. Vừa nhún nhảy, cười đó với bài hát All Izz Well vui nhộn, tim khán giả đã phải thắt lại với cảnh treo cổ của chàng sinh viên tội nghiệp Lobo. 3 Idiots đề cập đến một vấn nạn của xã hội hiện đại nói chung, của học đường nói riêng, đó là tỉ lệ tự tử ngày càng tăng. Học sinh trở nên mong manh hơn đối với cuộc sống chính các em. Trách nhiệm rất lớn thuộc về nhà trường, vốn phải là nơi tạo ra niềm hứng khởi, nay lại là nhà máy tạo ra những áp lực – kẻ giết người thầm lặng nguy hiểm.<br><br>3 Idiots chính là bộ phim ăn khách nhất của điện ảnh Ấn Độ khi thu về hơn 80 triệu USD trên toàn thế giới. 3 Idiots không thể trở thành một bộ phim nổi tiếng, giành Oscar hay được biết đến rộng rãi, nhưng nó có thể thay đổi cách nhìn cuộc sống và cách sống của bất kì một ai đó, những ai đã một lần đến với câu chuyện 3 chàng ngốc. Xem để sống lại khoảng thời gian đi học của mình, có nụ cười và cả nước mắt.",

    },
    {
        "id": "phim19",
        "ten": "ở nhà một mình (Home Alone)",
        "theLoai": "Phim hài",
        "nhaSanXuat": "Hughes Entertainment, Twentieth Century Fox",
        "noiDung": "Gia đình bác Frank đi nghỉ giáng sinh cùng gia đình của Kevin. Buổi sáng ra sân bay, cả nhà trể giờ, trong lúc lộn xộn, cậu bé Kenvin bị bỏ lại ở nhà một mình mà không ai hay biết. Trong lúc đó, hai tên trộm xấu xa tìm đến nhà cậu. Vượt qua sự sợ hãi ban đầu, một mình cậu với sự thông minh và lòng can đảm tuyệt vời chiến đấu với hai kẻ trộm để bảo vệ căn nhà của mình và khán giả được một dịp cười vỡ bụng...",
        "thoiLuong": "103 phút",
        "namSanXuat": "1990",
        "anh": "homeAlone.jpg",

            "IMDb": "7.5",
            "trailer": "jEDaVHmw7r4",
            "daoDien": "Chris Columbus",
            "dienVien": "Macaulay Culkin, Joe Pesci, Daniel Stern, John Heard, Catherine O'Hara, Roberts Blossom, John Candy",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "Nói tới Ở Nhà Một Mình chắc là không ai không biết nhỉ (9x bây giờ có biết không *thắc mắc*), phim này là siêu cường nổi tiếng trong những phim về Giáng Sinh luôn. Đây cũng là thành công to lớn nhất của Macaulay Caulkin, người được gọi là “thần đồng” sau vai diễn Kevin McCallister; đáng tiếc sau vai này thì ảnh tuột luốt đi đâu luôn.<br><br>Ở Nhà Một Mình kể về cậu bé Kevin McCallister có cá tính nghịch ngợm và có chút phiền phức, vì vậy mà cậu thường xuyên bị các anh chị lớn trong nhà bắt nạt, cuối cùng là trước khi cả gia đình đi du lịch Pháp thì Kevin đã ước quà Giáng Sinh của mình là “khỏi thấy mặt ai trong nhà nữa”. Ai dè trúng thiệt khi cậu bị bỏ quên ở nhà trong khi cả 1 đại gia đình vi vu đi Pháp. Ban đầu thì cậu sướng bỏ cha đi được và bày đủ trò nghịch ngợm, cho đến khi có hai tên trộm định vào trộm nhà cậu và xử luôn cả Kevin thì cậu quyết định sẽ tự bảo vệ ngôi nhà của mình.<br><br>Xét về mặt tâm lí nhân vật, mình cho rằng mạch tâm lí của Kevin trong Ở Nhà Một Mình rất hợp lí. Ban đầu là tâm lí chán ghét, chỉ mong cả nhà biến sớm nên khi phát hiện chỉ còn mình, Kevin rất là vui vẻ. Quậy phá tưng bừng, ăn uống bậy bạ (ăn cả 1 hũ kem tả pí lù to đùng). Và cậu rất sợ cái lò hơi ở dưới tầng hầm. Nhưng Kevin đã phát triển trong mấy ngày ở nhà một mình. Có lẽ vì phải đụng độ với lũ trộm mà cậu đã phải tự trưởng thành lên nhiều để bảo vệ nhà mình “như một người đàn ông chân chính”. Và mình thích cách phim miêu tả sự trưởng thành đó qua những chuỗi hành động tương-tự-nhau. Kevin từ ăn một hũ kem không có chất dinh dưỡng đến tự đặt Pizza đến tự làm nui để ăn, từ chuyện sợ người lạ ở siêu thị cho đến việc tự đi siêu thị một mình, từ việc sợ cái lò đến việc bảo cái lò “Im miệng” và đặc biệt là từ việc sợ ông lão hàng xóm đến việc trò chuyện thân mật với ông… Tất cả đều là những hành động tương-tự-nhau nhưng cái sau nó phát triển hơn cái trước, thể hiện một Kevin đã bớt trẻ con đi và biết tự lo cho mình hơn và biết quý trọng tình cảm gia đình hơn; kết hợp rất chặt chẽ và hợp lí.",

    },
    {
        "id": "phim20",
        "ten": "Deadpool",
        "theLoai": "Phim hành động, Phim hài",
        "nhaSanXuat": "Marvel Enterprises, TSG Entertainment, Twentieth Century Fox Film Corporation",
        "noiDung": "Deadpool xoay quanh anh chàng Wade Wilson, một người bị ung thư vô phương cứu chữa được thí nghiệm trở thành dị nhân với khả năng phục hồi siêu tốc giống Wolverine, tuy nhiên Deadpool được rất nhiều fan hâm mộ biết đến như là một nhân vật cực kỳ hài hước với cái mồm không bao giờ ngừng nói nhảm của hắn.",
        "thoiLuong": "106 phút",
        "namSanXuat": "2016",
        "anh": "dead.jpg",
        
            "trailer": "gtTfd6tISfw",
            "IMDb": "8.4",
            "daoDien": "Tim Miller",
            "dienVien": "Ryan Reynolds, Morena Baccarin, Ed Skrein, T. J. Miller, Gina Carano, Leslie Uggams, Brianna Hildebrand",
            "quocGia": "Mỹ",
            "ngonNgu":"Tiếng Anh",
            "review": "Sau 2 năm tu luyện hậu kỳ, Deadpool đã trở lại màn ảnh với một chiến dịch PR rầm rộ nhưng không kém phần hài hước và sáng tạo. Đổi lại, dù ra mắt ngay sau cơn sốt Avengers: Infinity War nhưng Deadpool vẫn không phụ lòng người hâm mộ với nhiều tình tiết hài hước, lầy lội, siêu bựa và cả hành động mãn nhãn người xem. Bên cạnh đó cũng không thể không kể tới các plot liên quan tới văn hóa đại chúng (pop culture) thú vị.<br><br>Trong vũ trụ điện ảnh Marvel (MCU), Deadpool (tên thật là Wade Wilson) xuất thân từ một lính đánh thuê, sau khi bị trọng thương và bị dùng làm thí nghiệm khoa học, cơ thể anh biến đổi dị thường. Bù lại, anh lại sở hữu nhiều kỹ năng siêu phàm, nhất là sự bất tử - Hãy nhớ siêu năng lực này khi xem Deadpool nhé! Trên màn ảnh, tài tử Ryan Reynolds tiếp tục đảm nhiệm vai diễn Deadpool theo cách mà như nhiều người nói là vai diễn sinh ra để dành cho anh, sau những gì anh đã thể hiện ở phần 1.<br><br>Tuy nhiên, trước khi bị cuốn vào cuộc phiêu lưu này thì Deadpool đã phải đối diện với một mất mát lớn nhất trong đời mình và khiến bản thân anh thay đổi theo hướng tích cực. Tất nhiên, Deadpool vẫn là một gã bựa nên kể cả khi muốn làm người tốt thì anh cũng không quên làm theo những cách lầy lội nhất: Làm điều đúng đắn thật phiền phức, nên nếu muốn chiến đấu vì lẽ phải thì thỉnh thoảng mày cần phải chơi đểu.  Bên cạnh đó, Deadpool 2 còn có sự tái ngộ của những nhân vật quen thuộc từng xuất hiện ở phần 1 trước đó như chàng tài xế taxi chịu chơi Dopinder (Karan Soni), bà dì Al mù (Leslie Uggams) nhưng cực kì can đảm và hổ báo (hãy để ý ở phần post-credit) và gã bartender Weasel (T.J. Miller).",
    },
    {
        "id": "phim21",
        "ten": "The Angry Birds Movie 2",
        "theLoai": "Phim hoạt hình, Phim hài",
        "nhaSanXuat": "Sony Pictures Animation, Rovio Entertainment",
        "thoiLuong": "97 phút",
        "namSanXuat": "2019",
        "anh": "angry2.jpg",
        "noiDung": "Trong Angry Birds Movie 2, Red (Jason Sudeikis) đã trở thành người hùng của đảo Chim và đang giao chiến cùng đảo Heo với sự giúp sức của người anh em Chuck (Josh Gad) và Bomb (Danny McBride). Khi cả bầy chim và heo cùng bị tấn công bởi loạt băng khổng lồ của Nữ hoàng băng giá Zeta (Leslie Jones) từ đảo Đại Bàng, Red và King Leonard Mudbeard (Bill Hader) đã đồng ý cùng liên minh để chống lại kẻ thù chung, với sự trợ lực từ Silver (Rachel Bloom), một sinh viên kỹ thuật xuất sắc.<br><br>Tất cả cùng phải lên kế hoạch để xâm nhập vào hang ổ của Zeta trước khi ả phá huỷ ngôi nhà của cả bọn bằng chiếc máy bắn băng lợi hại nhưng để làm được điều này, Red sẽ phải tạm gác lại nỗi bất an của mình và học cách làm việc cùng cả đội thay vì ‘chơi trò’ anh hùng một mình.",
        "IMDb": "6.4",
        "trailer": "fOcSqgxYOy4",
        "daoDien": "Clay Kaytis, Fergal Reilly,",
        "dienVien": "Jason Sudeikis, Josh Gad, Danny McBride, Bill Hader, Maya Rudolph, Peter Dinklage",
        "quocGia": "Mỹ",
        "ngonNgu":"Tiếng Anh",
        "review": "một hòn đảo đặc biệt là nơi sinh sống của các loài chim sặc sỡ và không biết bay chung sống vui vẻ, vô lo vô nghĩ. Chỉ trừ Red – chú chim đỏ mồ côi với cặp lông mày rậm rạp và kì dị, sinh ra đã là tâm điểm của mọi trò chọc ghẹo. Red lúc nào cũng có thể nổi giận, đá thúng đụng nia bất kể cây cối hay đồng loại. Vốn bị gắn mác lập dị và cáu kỉnh nên vào một ngày, Red đã quyết định thay đổi lại suy nghĩ của mọi người bằng cách làm chú hề mua vui cho chú chim nhỏ Timothy trong ngày sinh nhật. Tuy nhiên anh chàng lại làm mọi việc thêm tồi tệ vì chính Timothy bị bệnh sợ các chú hề. Chưa kể anh còn làm vỡ trứng của cặp vợ chồng nhà đó và suýt làm hỏng trứng, may mắn lại sinh ra một cậu bé biến anh thành người cha trong mắt cậu bé đó một cách không thân không phận, làm chia cắt tình cảm gia đình họ. Tòa cáo buộc Red phải vào Lớp học kiểm soát giận dữ do Matilda đảm nhiệm cùng với các học viên là Bomb, Terence và Chuck. Chỉ có Chuck và Bomb là tạm chấp nhận làm bạn với anh. Một ngày nọ, tại một bến tàu thuyền trên hòn đảo, binh đoàn lợn xanh – cầm đầu bởi Vua lợn xanh Leonard – đã đặt chân đến vùng đất nơi Red sinh sống với nguyên một con tàu hoành tráng chứa đựng biết bao điều thú vị. Tự xưng là các nhà thám hiểm hòa bình, những con lợn được cư dân trên đảo chấp nhận bởi chúng là giống loài duy nhất không phải chim trên đảo.<br><br>Sau lần tấn công ấy, Mighty Eagle đem toàn bộ quả trứng về lại cho cư dân và họ ngạc nhiên ra rằng ông có thật. Red, Chuck và Bomb gặp Mighty Eagle, bản thân ông nói rằng ông không thực sự lười biếng và ông đã cố tình làm cho họ mất niềm tin vào mình, để cho họ có niềm tin vào chính mình. Red được cư dân chim ca ngợi như một anh hùng, xây dựng lại ngôi nhà mới cho anh ở trong làng (trước đây nhà anh ở bãi biển vì bị trục xuất). Trong một đoạn hậu kết phim, tất cả các con lợn vẫn sống sót sau khi thành phố của chúng bị phá hủy và chúng đang xây dựng lại thành phố, thậm chí còn hát theo ca khúc I Will Survive. Trong khi đó, Leonard đang lên một kế hoạch mới để đánh cắp những quả trứng. Trong một đoạn hậu kết phim khác, bộ ba chim xanh Jay, Jake, Jim đã thể hiện năng lực phân ba khi bay lên trời bằng cây ná cao su khổng lồ đã được sửa chữa lại.",

    },
    {
        "id": "phim22",
        "ten": "The Angry Birds Movie",
        "theLoai": "Phim hoạt hình, Phim hài",
        "nhaSanXuat": "Sony Pictures Animation, Rovio Entertainment",
        "noiDung": "Phim Những Chú Chim Giận Dữ bắt đầu bằng cuộc sống yên bình và vui vẻ của những chú chim trong một hòn đảo. Ngay từ đầu trailer vang lên ca khúc Close To You của nhóm Carpenters với câu hát Why do birds suddenly appear... như vô cùng thích hợp cho bộ phim này, mang hàm ý cho câu hỏi tụi chim này ở đâu chui ra vậy?<br><br>Tiếp theo đó là bài nhạc Bad của Michael Jackson vang lên làm nền cho những trò nghịch ngợm quậy phá của lũ chim. Ví dụ khi cả bọn tâm sự với nhau, con chim màu đen nói Mỗi lần tao thấy buồn là tao thường nổ tung. Rất hấp dẫn! Dĩ nhiên là trong phim cũng không thể thiếu sự góp mặt của bầy heo màu xanh lá cây và những khối thuốc nổ TNT.",
        "thoiLuong": "100 phút",
        "namSanXuat": "2016",
        "anh": "angry1.jpg",
        "IMDb": "7.0",
        "trailer": "T0HYmfDsmbk",
        "daoDien": "Clay Kaytis, Fergal Reilly",
        "dienVien": "Jason Sudeikis, Josh Gad, Danny McBride, Bill Hader, Maya Rudolph, Peter Dinklage",
        "quocGia": "Mỹ",
        "ngonNgu":"Tiếng Anh",
        "review": "Tại Đảo Chim, một hòn đảo đặc biệt là nơi sinh sống của các loài chim sặc sỡ và không biết bay chung sống vui vẻ, vô lo vô nghĩ. Chỉ trừ Red – chú chim đỏ mồ côi với cặp lông mày rậm rạp và kì dị, sinh ra đã là tâm điểm của mọi trò chọc ghẹo. Red lúc nào cũng có thể nổi giận, đá thúng đụng nia bất kể cây cối hay đồng loại. Vốn bị gắn mác lập dị và cáu kỉnh nên vào một ngày, Red đã quyết định thay đổi lại suy nghĩ của mọi người bằng cách làm chú hề mua vui cho chú chim nhỏ Timothy trong ngày sinh nhật. Tuy nhiên anh chàng lại làm mọi việc thêm tồi tệ vì chính Timothy bị bệnh sợ các chú hề. Chưa kể anh còn làm vỡ trứng của cặp vợ chồng nhà đó và suýt làm hỏng trứng, may mắn lại sinh ra một cậu bé biến anh thành người cha trong mắt cậu bé đó một cách không thân không phận, làm chia cắt tình cảm gia đình họ. Tòa cáo buộc Red phải vào Lớp học kiểm soát giận dữ do Matilda đảm nhiệm cùng với các học viên là Bomb, Terence và Chuck. Chỉ có Chuck và Bomb là tạm chấp nhận làm bạn với anh. Một ngày nọ, tại một bến tàu thuyền trên hòn đảo, binh đoàn lợn xanh – cầm đầu bởi Vua lợn xanh Leonard – đã đặt chân đến vùng đất nơi Red sinh sống với nguyên một con tàu hoành tráng chứa đựng biết bao điều thú vị. Tự xưng là các nhà thám hiểm hòa bình, những con lợn được cư dân trên đảo chấp nhận bởi chúng là giống loài duy nhất không phải chim trên đảo.<br><br>Sau lần tấn công ấy, Mighty Eagle đem toàn bộ quả trứng về lại cho cư dân và họ ngạc nhiên ra rằng ông có thật. Red, Chuck và Bomb gặp Mighty Eagle, bản thân ông nói rằng ông không thực sự lười biếng và ông đã cố tình làm cho họ mất niềm tin vào mình, để cho họ có niềm tin vào chính mình. Red được cư dân chim ca ngợi như một anh hùng, xây dựng lại ngôi nhà mới cho anh ở trong làng (trước đây nhà anh ở bãi biển vì bị trục xuất). Trong một đoạn hậu kết phim, tất cả các con lợn vẫn sống sót sau khi thành phố của chúng bị phá hủy và chúng đang xây dựng lại thành phố, thậm chí còn hát theo ca khúc I Will Survive. Trong khi đó, Leonard đang lên một kế hoạch mới để đánh cắp những quả trứng. Trong một đoạn hậu kết phim khác, bộ ba chim xanh Jay, Jake, Jim đã thể hiện năng lực phân ba khi bay lên trời bằng cây ná cao su khổng lồ đã được sửa chữa lại.",
    },
    {
        "id": "phim23",
        "ten": "Men in Black: International",
        "theLoai": "Phim hài, Phim viễn tưởng, Phim hành động",
        "nhaSanXuat": "Columbia Pictures, Sony Pictures Entertainment (SPE), Amblin Entertainment",
        "noiDung": "Bấy lâu nay, Đặc vụ Áo Đen luôn là những người hùng thầm lặng “ngầu” nhất, bảo vệ Trái Đất khỏi những hiểm họa xấu xa ngoài hành tinh. Trong cuộc phiêu lưu mới này, họ phải đối mặt với mối đe dọa mang tính toàn cầu lớn nhất từ trước đến giờ: truy tìm điệp viên hai mang ẩn mình trong tổ chức Men In Black.",
        "thoiLuong": "110 phút",
        "namSanXuat": "2019",
        "anh": "Mib.jpg",
        "IMDb": "5.4",
        "trailer": "ESruleKcsCI",
        "daoDien": "F. Gary Gray",
        "dienVien": "Chris Hemsworth, Tessa Thompson, Rebecca Ferguson, Kumail Nanjiani, Rafe Spall, Laurent Bourgeois, Larry Bourgeois, Emma Thompson, Liam Neeson",
        "quocGia": "Mỹ",
        "ngonNgu":"Tiếng Anh",
        "review": "Chuỗi phim Men In Black rất thành công về tổ chức đặc vụ chuyên giải quyết các vấn đề kỳ lạ, liên quan đến người ngoài hành tinh. Họ hoạt động bí mật, bảo vệ con người khỏi các sinh vật ngoài trái đất và xóa ký ức của nhân loại. Với hai gương mặt đại diện biệt đội áo đen là Will Smith- Tommy Lee Jones, những gã mặc đồ đen đã càn quét phòng vé với tổng doanh thu ba phần phim lên đến hơn 1,6 tỷ $.<br><br> Nhiều năm sau MIB 3, đặc vụ áo đen tái xuất với phần ngoại truyện. Chris Hemsworth, Tessa Thompson, Liam Neelson là những cái tên được chọn để tiếp tục sự nghiệp mặc đồ đen. Thế nhưng, lần này, trách nhiệm cứu lấy thế giới không phải giao cho bộ đôi lưng dài vai rộng chuyên đóng hành động “thần Sấm” và “ông bố Taken”, mà là cô nàng Tessa Thompson- được đông đảo khán giả toàn cầu biết đến khi đảm nhận vai Valkyrie trong vũ trụ điện ảnh Marvel.<br><br>Bị trừ về cốt truyện nhưng điểm cộng cho kịch bản của bộ đôi Matt Holloway- Art Marcum chính là sự hài hước “trên từng cây số”. Chris Hemsworth và Tessa Thompson “tung hứng” hoàn hảo khiến người xem không thể nhịn cười. Hầu như ở từng phân cảnh đều có một câu thoại gây hài chất lượng. Điều này lý giải việc khán giả thích Men In Black: International mặc dù giới phê bình thẳng tay cho điểm thấp.",
    },
    {
        "id": "phim24",
        "ten": "Câu truyện đồ chơi Phần 4(Toy Story 4)",
        "theLoai": "Phim hoạt hình",
        "nhaSanXuat": "Pixar Animation Studios, Walt Disney Pictures",
        "noiDung": "Chín năm trước khi toàn bộ những đồ chơi còn ở với Andy, R.C. bị một cơn mưa cuốn đi. Woody giải cứu thành công với sự giúp đỡ của các đồ chơi khác, tuy nhiên do không hay biết nên Bo Peep và một vài đồ chơi khác bị Molly, em gái của Andy đem đi; dù Woody đã cố gắng giải cứu cô, Bo mới khước từ bảo rằng đồ chơi cũng có lúc phải cho đi, rồi họ ôm nhau chia tay.<br><br>Hai năm sau khi Andy góp đồ chơi cho Bonnie, Woody và những đồ chơi khác đang sống hạnh phúc bên nhau. Vì lo lắng chuyện Bonnie sẽ cảm thấy sợ hãi khi vào lớp định hướng nhà trẻ, sau khi nhìn thấy Bonnie bật khóc, Woody chuồn vào ba lô của cô bé và chứng kiến cảnh Bonnie dè dặt trước bạn mới của mình. Woody tìm cách lôi hàng tá đồ bỏ đi trong thùng rác và đặt lên bàn của Bonnie, và cô nhận ra được rồi tự tay làm món đồ chơi của mình đặt tên là Forky. Sau khi Bonnie đặt Forky viết tên của mình lên giày của Forky và đặt vào trong ba lô của mình, Woody chui vào trong theo, đột nhiên món đồ chơi Forky trỗi dậy làm cho anh hoảng hốt.",
        "thoiLuong": "100 phút",
        "namSanXuat": "2019",
        "anh": "toy.jpg",
        "IMDb": "6.5",
        "trailer": "CjpegSt3Bzc",
        "daoDien": "Josh Cooley",
        "dienVien": "Tom Hanks, Tim Allen, Joan Cusack",
        "quocGia": "Mỹ",
        "ngonNgu":"Tiếng Anh",
        "review": "Sau khi Woody giới thiệu Forky cho toàn bộ đồ chơi của Bonnie nghe, tất cả mọi người đều lại gần hoan nghênh, đột nhiên Forky nổi loạn, nghĩ rằng cậu ta chỉ được làm từ rác chứ không phải đồ chơi, Woody bất quá đành phải ngăn chặn cậu ta chui vào thùng rác. Trong một chuyến đi chơi với gia đình Bonnie và đồ chơi của cô bé, Forky nhảy ra khỏi cửa sổ, khiến Woody đi theo cậu ta ra ngoài. Woody thuyết phục Forky về những niềm vui khi trở thành một món đồ chơi, và họ dùng xe du lịch (RV) đi đến công viên tại một thị trấn gần đó, nơi Bonnie và bố mẹ cô sẽ ở.<br><br>Đến thị trấn, Woody nhìn thấy đèn của Bo tại một Cửa hàng đồ cổ. Tìm kiếm Bo bên trong, anh và Forky bắt gặp một con búp bê tên Gabby và những con rối nhỏ của cô, Bensons. Gabby đề nghị đưa họ đến Bo, nhưng sớm tiết lộ kế hoạch thực sự của cô là mong muốn có được hộp âm thanh của Woody, vì cái của cô đã bị hỏng và cho rằng nguyên nhân đó khiến không có đứa trẻ nào thèm nhận cô. Khi Bonnie và cha mẹ cô vào cửa hàng, Woody và Forky cố gắng trốn thoát, nhưng Forky bị Gabby bắt giữ. Vào lúc Woody trốn khỏi cửa hàng, RV của Bonnie đã rời đi mà không có Forky, và Woody nhận ra rằng mình đã bỏ lại Forky phía sau. Dọc đường đến lễ hội, Woody bắt gặp một cô bé và vô tình dẫn đến cuộc tái ngộ với Bo, Bo kể rằng mình đã trở thành dân du mục hơn bảy năm. Với bạn đồng hành của Bo, một cảnh sát thu nhỏ tên là Giggle McDimples, họ đi theo con đường qua một lễ hội gần đó để giải cứu Forky khỏi cửa hàng đồ cổ.",
    },
    {
        "id": "phim25",
        "ten": "Cuộc hội ngộ kỳ diệu( Coco)",
        "theLoai": "Phim hoạt hình",
        "nhaSanXuat": "Pixar Animation Studios, Walt Disney Pictures",
        "noiDung": "Bộ phim này kể về hành trình của Miguel, một cậu bé say mê những giai điệu nhưng lại sinh trưởng trong một gia đình cấm đoán sự xuất hiện của âm nhạc. Miguel luôn nung nấu giấc mơ trở thành một nhạc sĩ nổi tiếng giống như thần tượng Ernesto de la Cruz. Tuy nhiên, truyền thống ngang trái của gia đình đã khiến cậu không thể chứng minh tài năng của mình.<br><br>Rũ bỏ thực tế phũ phàng, Miguel tìm thấy chính mình ở Vùng Đất Linh Hồn tuyệt đẹp và đầy sắc màu sau một chuỗi sự kiện huyền bí. Trong hành trình khám phá vùng đất mới, Miguel gặp gỡ “chuyên gia xảo quyệt” Hector. Cả hai cùng tạo nên chuyến phiêu lưu kỳ diệu để lật mở những bí mật chưa được tiết lộ về lịch sử của gia đình Miguel.",
        "thoiLuong": "127 phút",
        "namSanXuat": "2017",
        "anh": "coco.jpg",
        "IMDb": "8.5",
        "trailer": "sVXyZB3pJGQ",
        "daoDien": "Lee Unkrich, Adrian Molina",
        "dienVien": "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt, Alanna Ubach, Renée Victor",
        "quocGia": "Mỹ",
        "ngonNgu":"Tiếng Anh",
        "review": "Imelda Rivera là vợ của một nhạc sĩ, sống tại Santa Cecilia, Mexico. Chồng của Imelda đã bỏ cô và con gái, Coco, theo đuổi sự nghiệp âm nhạc của cá nhân. Vì thế, Imelda đã cấm âm nhạc trong gia đình và mở một cửa hàng kinh doanh giày gia truyền. Thời điểm hiện tại, chắt trai của bà, Miguel, hiện đang sống với bà cố Coco (con gái của Imelda) và gia đình nhiều thế hệ của họ. Cậu mơ ước trở thành một nhạc sĩ huyền thoại và tài ba như Ernesto de la Cruz, một diễn viên nổi tiếng và cũng là một ca sĩ cùng thời với Imelda. Một ngày nọ, Miguel tình cờ làm vỡ bức ảnh của Imelda trên bàn thờ gia đình và đã mở nó, phát hiện ra rằng chồng của cụ bà Imelda (có khuôn mặt bị rách) đang cầm cây đàn guitar nổi tiếng của Ernesto và nghĩ rằng, ông sơ của cậu chính là ca sĩ mà cậu vẫn luôn ngưỡng mộ.<br><br>Miguel biện luận với bà Elena của mình và bỏ đi để tham gia một chương trình tài năng trong Ngày lễ dành cho người đã khuất. Cậu bước vào lăng mộ của Ernesto và ăn cắp cây guitar của ông để sử dụng trong chương trình tài năng, nhưng bất ngờ cậu trở nên vô hình đối với tất cả mọi người trong làng. Tuy nhiên, cậu lại có thể nhìn thấy và được nhìn thấy bởi con chó Xoloitzcuintli của mình, Dante và những người thân đã qua đời của cậu (chỉ còn trong hình dạng bộ xương người) - họ đến từ Vùng đất của người chết và đang trên đường tới thăm gia đình trong ngày lễ. Gặp cậu ở đó, họ nhận ra rằng Imelda không thể đến thăm gia đình vì Miguel đã tháo bức ảnh của cô ấy ra khỏi khung kính trên bàn thờ. Miguel khám phá ra rằng cậu bé đã bị nguyền rủa vì ăn cắp đồ vật của người đã mất, cậu phải trở về Vùng đất của người còn sống trước khi mặt trời mọc nếu không cậu sẽ trở thành một trong số những người chết. Để làm được như vậy, cậu phải được ban phước lành từ một thành viên trong gia đình của mình bằng cách sử dụng hoa cúc Aztec vì cánh hoa có thể đẩy lùi lời nguyền cho tội ăn cắp chiếc guitar của Ernesto. Imelda ban phước cho Miguel nhưng với điều kiện là cậu phải từ bỏ mọi hoạt động âm nhạc khi cậu trở về Vùng đất của người còn sống; Miguel từ chối và cố gắng tìm kiếm sự trợ giúp của Ernesto.",
    },
    {
        "id": "phim26",
        "ten": "Chú hề ma quái 2 (IT 2)",
        "theLoai": "Phim kinh dị",
        "nhaSanXuat": "KatzSmith Productions, Lin Pictures, New Line Cinema",
        "noiDung": "It Chapter Two (Gã Hề Ma Quái 2) vẫn là câu chuyện về những cô cậu bé của nhóm The Losers Club, lúc này đã trưởng thành và đối mặt với vô số vấn đề trong cuộc sống. Chưa dừng lại ở đó, ám ảnh ma hề Pennywise cứ 27 năm lại xuất hiện một lần tại thị trấn Derry buộc 7 cô cậu bé ngày nào phải tiếp tục cuốn vào cuộc chạm trán tiếp theo giữa hai bên thiện và ác.<br><br>Mặc dù có thể cả nhóm đã trưởng thành và khôn ngoan hơn, cuộc chiến của họ với Pennywise vẫn còn đó những hậu quả bất ngờ, thậm chí khiến một số thành viên phải trải qua đau đớn đến tột cùng.        ",
        "thoiLuong": "217 phút",
        "namSanXuat": "2019",
        "anh": "IT2.jpg",
        "IMDb": "6.9",
        "trailer": "qblBGRBtmU0",
        "daoDien": "Andy Muschietti,",
        "dienVien": "Jaeden Lieberher, Sophia Lillis, Bill Skarsgård, Jeremy Ray Taylor",
        "quocGia": "Mỹ",
        "ngonNgu":"Tiếng Anh",
        "review": "Phim kể về bảy đứa trẻ sống tại bang Maine và hành trình khám phá, tiêu diệt một thực thể ngoài hành tinh có nhiều khả năng đặc biệt là It (tên tiếng Việt: Nó) thường hay xuất hiện trong hình dạng gã hề Pennywise.<br><br>Tự đặt tên nhóm là Hội kém cỏi, những đứa trẻ nhận ra rằng tất cả chúng đang bị đe dọa bởi cùng một thực thể. Chúng xác định rằng Pennywise biến hóa thành những gì chúng sợ, hắn thức dậy cứ sau 27 năm để làm hại trẻ em ở thị trấn Derry trước khi quay lại ngủ đông và di chuyển thông qua hệ thống cống ngầm, tất cả đường cống đều dẫn đến một cái giếng hiện đang ở dưới ngôi nhà bỏ hoang số 29 trên đường Neibolt. Sau một cuộc tấn công của Pennywise, cả nhóm mạo hiểm đến ngôi nhà hoang để đối đầu với hắn, từng đứa trẻ tách ra và bị hù dọa. Khi chúng tập hợp lại, Beverly đâm vào đầu Pennywise, buộc gã hề phải rút lui. Sau cuộc chạm trán, cả nhóm bắt đầu muốn bỏ cuộc, chỉ có Bill và Beverly kiên quyết đòi tiếp tục chiến đấu với gã hề.<br><br>Vài tuần sau, sau khi Beverly chống lại ông bố kỳ quặc của mình, cô bị Pennywise bắt cóc. Hội kém cỏi tập hợp lại và quay trở lại ngôi nhà hoang đường Neibolt để giải cứu cô. Henry Bowers, người đã giết bố mình sau khi bị gã hề ám ảnh đến điên loạn, tấn công cả nhóm. Mike chiến đấu lại và xô Bowers xuống cái giếng sâu thăm thẳm. Hội kém cỏi đi xuống đường cống và tìm thấy hang ổ dưới lòng đất của gã hề, nơi chứa rất nhiều đạo cụ làm xiếc và đồ đạc của trẻ em, xung quanh là xác của những đứa trẻ bị mất tích bay lơ lửng giữa không trung. Beverly, đang bị hôn mê sau khi tiếp xúc với hình dạng thật của gã hề, tỉnh lại khi Ben hôn cô. Bill gặp Georgie, nhưng nhận ra rằng cậu bé là do Pennywise biến hóa. Pennywise tấn công cả nhóm và bắt Bill làm con tin, đề nghị tha mạng cho những đứa trẻ còn lại nếu chúng để hắn giữ Bill. Hội kém cỏi từ chối điều này và khẳng định tình bạn của chúng, vượt qua những nỗi sợ hãi khác nhau của chúng. Sau một trận chiến ngắn ngủi, cả nhóm đánh bại Pennywise và hắn rút lui, Bill tuyên bố rằng hắn sẽ chết đói trong thời gian ngủ đông. Sau khi tìm thấy phần còn lại của chiếc áo mưa của Georgie, Bill cuối cùng cũng chấp nhận cái chết của em trai mình và được bạn bè an ủi.",
    },
    {
        "id": "phim27",
        "ten": "Hellboy",
        "theLoai": "Phim kinh dị, Phim hài",
        "nhaSanXuat": "Summit Entertainment, Millennium Films, Boyana Film Studios",
        "noiDung": "Được chuyển thể dựa trên bộ truyện tranh cùng tên nổi tiếng của tác giả Mike Mignola, phần “reboot” Hellboy là cuộc chiến giữa “Quỷ đỏ” (David Harbour - Stranger Things) và một ác nữ cổ xưa (Milla Jovovich - Resident Evil) đang lên kế hoạch tiêu diệt loài người.<br><br>",
        "thoiLuong": "120 phút",
        "namSanXuat": "2019",
        "anh": "hell.jpg",
        "IMDb": "5.4",
        "trailer": "dt5g5_1cKVk",
        "daoDien": "Neil Marshall",
        "dienVien": "David Harbour, Milla Jovovich, Ian McShane, Sasha Lane, Daniel Dae Kim, Thomas Haden Church",
        "quocGia": "Mỹ",
        "ngonNgu":"Tiếng Anh",
        "review": "Hellyboy lần này là bản reboot lại nên khán giả hoàn toàn có thể dễ dàng hiểu được những câu chuyện trong phim mà không gặp phải khó khăn gì. Một câu chuyện mới giúp khán giả có thể hiểu rõ được xuất thân của Quỷ đỏ - Hellboy.<br><br>Hellboy vẫn là anh chàng sở hữu cơ bắp khổng lồ với những sức mạnh phi thường. Anh cùng với cha mình tham gia vào tổ chức điều tra các thế lực hắc ám đang tồn tại khắp nơi. Sau nhiều năm hành hiệp trượng nghĩa, Hellboy được một tổ chức tại Anh triệu tập – đó là nơi cha anh từng tham gia hoạt động nhiều năm trước.<br><br>Đảm nhân vai chính của bộ phim là nam diễn viên David Harbour vai Hellboy. Anh tiếp tục hóa thân mình vào hình tượng một người hùng khổng lồ với những màn ra tay dứt khoát và đầy mạnh mạo. Tuy nhiên diễn xuất của anh rất khó đánh giá vì khuôn mặt của anh đã bị hóa trang đến biến dạng.<br><br>HÌNH ẢNH, ÂM THANH:<br>Phần hình ảnh của Hellboy chỉ được đánh giá ở mức độ khá, bộ phim sử dụng khá nhiều khung hình tối và tương phản màu sắc. Song lựa chọn này không được đánh giá cao khi luôn mang đến cảm giác mịt mù cho khán giả.<br><br>Âm nhạc là phần nhận được nhiều lời khen nhất từ phía khán giả với những giai điệu sôi động, được lồng ghép khéo léo với các tình tiết trong phim, hoàn toàn phù hợp với tính cách tưng tửng của anh chàng Quỷ đỏ.<br><br>KỸ XẢO:<br>Kỹ xảo của bộ phim vì bị cắt khá nhiều cảnh nên những phân cảnh xuất hiện trong phim chưa thể hiện được toàn bộ phần kỹ xảo của bộ phim. Tuy nhiên Touch Cinema nhận thấy những cảnh khác trong phim đều được xử lý khá tốt.",
    },
    {
        "id": "phim28",
        "ten": "Tần số chết (0.0Hz)",
        "theLoai": "Phim kinh dị",
        "nhaSanXuat": "chưa rõ",
        "noiDung": "0.0MHZ – TẦN SỐ CHẾT lấy cảm hứng từ bộ webtoon kinh dị cùng tên của họa sĩ Jang Jak. Bộ phim theo chân nhóm bạn có “sở thích” săn ma tìm đến một ngôi nhà hoang để kiểm chứng một nghiên cứu khoa học: khi sóng não con người chạm tới tần số 0.00MHz, đó chính là thời điểm mà chúng ta có thể nhìn thấy “ma quỷ”. Từ đó, mọi chuyện kỳ lạ bắt đầu xảy đến với từng thành viên, họ buộc phải quay trở lại ngôi nhà đó một lần nữa để kết thúc tất cả.",
        "thoiLuong": "120 phút",
        "namSanXuat": "2019",
        "anh": "oo.jpg",
        "IMDb": "5.4",
        "trailer": "luPuMrBww2w",
        "daoDien": "Yoo Sun-Dong",
        "dienVien": "chưa rõ",
        "quocGia": "Hàn Quốc",
        "ngonNgu":"Tiếng Hàn",
        "review": "Phim Tần Số Chết (0.0 MHz) được lấy cảm hứng từ webtoon kinh dị cùng tên của họa sĩ Jang Jak. Bạn nào nếu muốn đọc có thể tìm trên google với từ khóa Webtoon Tần Số Chết, tôi cũng mới chỉ đọc được mấy chapter đầu. Bộ phim là hành trình săn ma của một nhóm các bạn trẻ trong câu lạc bộ chuyên tìm hiểu về các sự kiện bí ẩn để kiểm chứng một nghiên cứu khoa học: Khi sóng não con người chạm tới tần số 0.0 MHz, đó là thời điểm ma quỷ xuất hiện và chúng ta có thể nhìn thấy các linh hồn. Nhưng cũng từ đó, họ đã phải trả giá khi hàng loạt chuyện kỳ quái đã xảy đến với các thành viên.<br><br>Sở hữu nội dung có phần mới lạ nên ngay từ khi xuất hiện, Tần Số Chết đã giành được sự quan tâm từ các khán giả, trong đó có tôi. Rồi sau đó, việc phim bị Bộ Văn hóa Thể thao và Du lịch cấm chiếu lại càng đẩy sự tò mò, háo hức của mọi người lên cao hơn bao giờ hết. Bởi phim phải ghê rợn thế nào thì mới bị kiểm duyệt thế chứ. Nhưng sau khi kiên nhẫn ngồi xem hết phim, tôi chợt nhận ra, có lẽ nguyên nhân thật sự khiến phim Tần Số Chết bị cấm chiếu là bởi vì nó quá…dở.<br><br>Nói chung xem đến gần nửa tiếng mà vẫn có biến gì là tôi đã thấy nghi nghi rồi. Nội dung phim nói về 5 thanh niên chơi dại muốn gặp ma rồi cuối cùng bị ma ám thật. Và tất cả cũng chỉ có thế. Mà lúc trước chính Han Seok nói là “Hãy xuất hiện đại thứ gì đó đi cũng được” thế mà lúc ma đến thì lại co giò chạy hết với nhau. Khó chiều lòng mấy người ghê.",
    },

]
localStorage.setItem("DSPhim",JSON.stringify(danhSachPhim));
console.log(danhSachPhim);
